apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    rabbitmq.com/topology-allowed-namespaces: picca-ai-prototype,picca
  labels:
    app: rabbitmq-default
    app.kubernetes.io/name: rabbitmq-default
  name: default
  namespace: rabbitmq
spec:
  image: docker.io/rabbitmq:4.3.5-management
  persistence:
    storage: 10Gi
  replicas: 1
  resources:
    limits:
      cpu: "2"
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 512Mi
