apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-agent-certs
  namespace: argocd
spec:
  project: berry
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/walnuts1018/infra
    targetRevision: clusterapi
    path: k8s/_argocd/agent/certs
    directory:
      recurse: true
      jsonnet: {}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - ServerSideApply=true
    - FailOnSharedResource=true
