replicaCount: 1

useUnprivilegedImage: true

readinessProbe:
  enabled: true

livenessProbe:
  enabled: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: "1"
    memory: 2Gi

persistence:
  size: 10Gi
  storageClassName: longhorn

snapshotPersistence:
  enabled: true
  size: 10Gi
  storageClassName: longhorn

metrics:
  serviceMonitor:
    enabled: true
