apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oekaki-dengon-game-5424d8
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: postgres
      secretKey: postgres-admin-password
    - remoteRef:
        key: postgres_passwords
        property: oekaki_dengon_game
      secretKey: postgres-user-password
    - remoteRef:
        key: oekaki-dengon-game
        property: minio-access-key
      secretKey: minio-access-key
    - remoteRef:
        key: oekaki-dengon-game
        property: minio-secret-key
      secretKey: minio-secret-key
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: oekaki-dengon-game-5424d8
