apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oekaki-dengon-game-fb4618
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: postgres
      secretKey: postgres-admin-password
    - remoteRef:
        key: postgres_passwords
        property: oekaki_dengon_game
      secretKey: postgres-user-password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: oekaki-dengon-game-fb4618
    template:
      data:
        postgres-admin-password: '{{ index . "postgres-admin-password" }}'
        postgres-user-password: '{{ index . "postgres-user-password" }}'
      engineVersion: v2
      type: Opaque
