apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oekaki-dengon-game-949d6c
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: postgres
      secretKey: postgres-admin-password
    - remoteRef:
        key: postgres_passwords
        property: oekaki_dengon_game
      secretKey: postgres-user-password
    - remoteRef:
        key: seaweedfs
        property: oekaki_dengon_game_secretkey
      secretKey: minio-secret-key
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: oekaki-dengon-game-949d6c
    template:
      data:
        minio-access-key: oekaki_dengon_game
        minio-secret-key: '{{ index . "minio-secret-key" }}'
        postgres-admin-password: '{{ index . "postgres-admin-password" }}'
        postgres-user-password: '{{ index . "postgres-user-password" }}'
      engineVersion: v2
      type: Opaque
