apiVersion: v1
data:
  disk-cleaner.sh: |
    #!/bin/sh

    USE=$(df /tmp/renovate/cache | awk 'NR==2{print $5}')
    IUSE=$(df -i /tmp/renovate/cache | awk 'NR==2{print $5}')

    echo "Disk usage: $USE, Inode usage: $IUSE"

    if [ "${USE%?}" -gt 75 ] || [ "${IUSE%?}" -gt 75 ]; then
      echo "Cleaning cache..."
      rm -rf /tmp/renovate/cache
    fi
immutable: true
kind: ConfigMap
metadata:
  labels:
    app: renovate
    app.kubernetes.io/name: renovate
  name: renovate-scripts-b52e1d
  namespace: renovate
