apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: renovate-e885e8
spec:
  data:
    - remoteRef:
        key: renovate
        property: github_token
      secretKey: github-token
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: renovate-e885e8
