apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-fcf653
spec:
  data:
    - remoteRef:
        key: renovate
        property: github_app_id
      secretKey: github-app-id
    - remoteRef:
        key: renovate
        property: github_app_installation_id
      secretKey: github-app-installation-id
    - remoteRef:
        key: renovate
        property: github_app_private_key
      secretKey: github-app-private-key
    - remoteRef:
        key: renovate
        property: pat_for_ghcr
      secretKey: pat-for-ghcr
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: renovate-fcf653
    template:
      engineVersion: v2
      type: Opaque
