apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seaweedfs-default-filer-config-a6ae80
  namespace: seaweedfs
spec:
  data:
    - remoteRef:
        key: scylladb
        property: seaweedfs
      secretKey: scylladb_password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: seaweedfs-default-filer-config-a6ae80
    template:
      data:
        filer.toml: |
          [leveldb2]
          enabled = false

          [cassandra2]
          enabled = true
          keyspace = "seaweedfs"
          hosts = ["scylla-cluster-client.databases.svc:9142"]
          username = "seaweedfs"
          password = "{{ .scylladb_password }}"
          tls_ca_file = "/etc/seaweedfs/scylladb-ca/ca.crt"
          tls_client_crt_file = "/etc/seaweedfs/scylladb-client/tls.crt"
          tls_client_key_file = "/etc/seaweedfs/scylladb-client/tls.key"
          localDC = "iwakura"
      engineVersion: v2
      type: Opaque
