apiVersion: seaweed.seaweedfs.com/v1
kind: S3Credentials
metadata:
  name: terraform
  namespace: seaweedfs
spec:
  identityRef:
    name: terraform
  reclaimPolicy: Retain
  seaweedRef:
    name: seaweedfs-default
  secretRef:
    accessKeyField: terraform_accesskey
    name: seaweedfs-default-s3-credentials-4f5552
    secretKeyField: terraform_secretkey
---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Credentials
metadata:
  name: misskey
  namespace: seaweedfs
spec:
  identityRef:
    name: misskey
  reclaimPolicy: Retain
  seaweedRef:
    name: seaweedfs-default
  secretRef:
    accessKeyField: misskey_accesskey
    name: seaweedfs-default-s3-credentials-4f5552
    secretKeyField: misskey_secretkey
---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Credentials
metadata:
  name: oekaki-dengon-game
  namespace: seaweedfs
spec:
  identityRef:
    name: oekaki-dengon-game
  reclaimPolicy: Retain
  seaweedRef:
    name: seaweedfs-default
  secretRef:
    accessKeyField: oekaki_dengon_game_accesskey
    name: seaweedfs-default-s3-credentials-4f5552
    secretKeyField: oekaki_dengon_game_secretkey
---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Credentials
metadata:
  name: stalwart
  namespace: seaweedfs
spec:
  identityRef:
    name: stalwart
  reclaimPolicy: Retain
  seaweedRef:
    name: seaweedfs-default
  secretRef:
    accessKeyField: stalwart_accesskey
    name: seaweedfs-default-s3-credentials-4f5552
    secretKeyField: stalwart_secretkey
