apiVersion: seaweed.seaweedfs.com/v1
kind: S3Credentials
metadata:
  name: mac-hatena
  namespace: seaweedfs
spec:
  identityRef:
    name: mac-hatena
  reclaimPolicy: Retain
  seaweedRef:
    name: seaweedfs-default
  secretRef:
    accessKeyField: accesskey
    name: seaweedfs-default-mac-hatena-credentials
    namespace: seaweedfs
    secretKeyField: secretkey
---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Credentials
metadata:
  name: maps-read
  namespace: seaweedfs
spec:
  identityRef:
    name: maps-read
  reclaimPolicy: Retain
  seaweedRef:
    name: seaweedfs-default
  secretRef:
    accessKeyField: AWS_ACCESS_KEY_ID
    name: maps-s3-credentials
    namespace: maps
    secretKeyField: AWS_SECRET_ACCESS_KEY
---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Credentials
metadata:
  name: misskey
  namespace: seaweedfs
spec:
  identityRef:
    name: misskey
  reclaimPolicy: Retain
  seaweedRef:
    name: seaweedfs-default
  secretRef:
    accessKeyField: accesskey
    name: seaweedfs-default-misskey-credentials
    namespace: seaweedfs
    secretKeyField: secretkey
---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Credentials
metadata:
  name: oekaki-dengon-game
  namespace: seaweedfs
spec:
  identityRef:
    name: oekaki-dengon-game
  reclaimPolicy: Retain
  seaweedRef:
    name: seaweedfs-default
  secretRef:
    accessKeyField: minio-access-key
    name: oekaki-dengon-game-s3-credentials
    namespace: oekaki-dengon-game
    secretKeyField: minio-secret-key
---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Credentials
metadata:
  name: stalwart
  namespace: seaweedfs
spec:
  identityRef:
    name: stalwart
  reclaimPolicy: Retain
  seaweedRef:
    name: seaweedfs-default
  secretRef:
    accessKeyField: s3_access_key
    name: stalwart-s3-credentials
    namespace: stalwart
    secretKeyField: s3_secret_access_key
---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Credentials
metadata:
  name: visual-regression-tracker
  namespace: seaweedfs
spec:
  identityRef:
    name: visual-regression-tracker
  reclaimPolicy: Retain
  seaweedRef:
    name: seaweedfs-default
  secretRef:
    accessKeyField: AWS_ACCESS_KEY_ID
    name: visual-regression-tracker-s3-credentials
    namespace: visual-regression-tracker
    secretKeyField: AWS_SECRET_ACCESS_KEY
