apiVersion: seaweed.seaweedfs.com/v1
kind: S3Identity
metadata:
  name: terraform
  namespace: seaweedfs
spec:
  name: terraform
  reclaimPolicy: Retain
  seaweedRef:
    name: seaweedfs-default
---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Identity
metadata:
  name: misskey
  namespace: seaweedfs
spec:
  name: misskey
  reclaimPolicy: Retain
  seaweedRef:
    name: seaweedfs-default
---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Identity
metadata:
  name: oekaki-dengon-game
  namespace: seaweedfs
spec:
  name: oekaki_dengon_game
  reclaimPolicy: Retain
  seaweedRef:
    name: seaweedfs-default
---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Identity
metadata:
  name: stalwart
  namespace: seaweedfs
spec:
  name: stalwart
  reclaimPolicy: Retain
  seaweedRef:
    name: seaweedfs-default
