apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-seaweedfs-default-volume-hdd-0
  namespace: seaweedfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 320Gi
  storageClassName: topolvm-hdd
  volumeMode: Filesystem
