apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: webtop-oidc-gateway
  namespace: webtop
spec:
  data:
    - remoteRef:
        key: terraform-external-secrets
        property: webtop-client-id
      secretKey: client-id
    - remoteRef:
        key: terraform-external-secrets
        property: webtop-client-secret
      secretKey: client-secret
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: webtop-oidc-gateway
    template:
      engineVersion: v2
      type: Opaque
