apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: influxdb
  namespace: databases
spec:
  hostnames:
    - influxdb.walnuts.dev
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway-system
  rules:
    - backendRefs:
        - kind: Service
          name: influxdb-influxdb2
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
