apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: influxdb-ingress
  namespace: databases
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: envoy-gateway-system
          podSelector:
            matchLabels:
              app.kubernetes.io/component: proxy
              app.kubernetes.io/managed-by: envoy-gateway
              app.kubernetes.io/name: envoy
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: fitbit-manager
          podSelector:
            matchLabels:
              app.kubernetes.io/name: fitbit-manager
      ports:
        - port: 8086
          protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: influxdb
      app.kubernetes.io/name: influxdb2
  policyTypes:
    - Ingress
