apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: teddy-bccea4
spec:
  data:
    - remoteRef:
        key: teddy
        property: AUTH_SECRET
      secretKey: AUTH_SECRET
    - remoteRef:
        key: teddy
        property: AUTH_ZITADEL_SECRET
      secretKey: AUTH_ZITADEL_SECRET
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: teddy-bccea4
