apiVersion: valkey.io/v1alpha1
kind: ValkeyCluster
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: picca-valkey
    app.kubernetes.io/name: picca-valkey
  name: picca-valkey
  namespace: picca
spec:
  persistence:
    size: 2Gi
  replicas: 2
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: 5m
      memory: 5Mi
  shards: 1
  users:
    - enabled: true
      name: default
      passwordSecret:
        keys:
          - valkey_password
        name: picca-00b20d
      permissions: +@all ~* &*
