apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rabbitmq-operator
resources:
- https://github.com/rabbitmq/cluster-operator/releases/download/v2.21.0/cluster-operator.yml
- https://github.com/rabbitmq/messaging-topology-operator/releases/latest/download/messaging-topology-operator-with-certmanager.yaml
