apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-config
  namespace: envoy-gateway-system
spec:
  provider:
    kubernetes:
      envoyDeployment:
        container:
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 8m
              memory: 96Mi
        replicas: 2
      envoyHpa:
        maxReplicas: 5
        metrics:
          - resource:
              name: memory
              target:
                averageUtilization: 100
                type: Utilization
            type: Resource
        minReplicas: 2
      envoyService:
        externalTrafficPolicy: Local
        loadBalancerIP: 192.168.12.138
        type: LoadBalancer
    type: Kubernetes
  telemetry:
    tracing:
      provider:
        backendRefs:
          - name: default-collector
            namespace: opentelemetry-collector
            port: 4317
        type: OpenTelemetry
      samplingRate: 100
