apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: picca-rabbitmq-user-credentials
  namespace: picca
spec:
  data:
    - remoteRef:
        key: terraform-external-secrets
        property: picca-rabbitmq-password
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: picca-rabbitmq-user-credentials
    template:
      data:
        password: '{{ .password }}'
        username: picca
      engineVersion: v2
      type: Opaque
