apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 98e96cb4d328154cc69e3c5d9c737180-helm
  namespace: argocd
spec:
  destination:
    namespace: gha-runner
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gha-runner-scale-set
    helm:
      releaseName: 98e96cb4d328154cc69e3c5d9c737180
      valuesObject:
        containerMode:
          type: dind
        controllerServiceAccount:
          name: gha-runner-controller-gha-rs-controller
          namespace: gha-runner-controller
        githubConfigSecret: gha-runner
        githubConfigUrl: https://github.com/walnuts1018/cloudflare-tunnel-operator
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.10.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - FailOnSharedResource=true
