plans:
  - id: admin
    name: Admin
    storageLimitBytes: null # 無制限

assignmentRules:
  - planId: admin
    expression: >
      "urn:zitadel:iam:org:project:roles" in userinfo &&
      "picca-admin" in userinfo["urn:zitadel:iam:org:project:roles"]
