apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: warrior-secret-0d336d
spec:
  data:
    - remoteRef:
        key: warrior
        property: client_id
      secretKey: client-id
    - remoteRef:
        key: warrior
        property: client_secret
      secretKey: client-secret
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: warrior-secret-0d336d
    template:
      engineVersion: v2
      type: Opaque
