apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: diode
  namespace: netbox
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: diode
      secretKey: db_password
    - remoteRef:
        key: diode
        property: redis_password
      secretKey: redis_password
    - remoteRef:
        key: diode
        property: diode_to_netbox_client_secret
      secretKey: diode_to_netbox_client_secret
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: diode
    template:
      data:
        DIODE_TO_NETBOX_CLIENT_SECRET: '{{ .diode_to_netbox_client_secret }}'
        POSTGRES_PASSWORD: '{{ .db_password }}'
        REDIS_PASSWORD: '{{ .redis_password }}'
        db-password: '{{ .db_password }}'
        redis-password: '{{ .redis_password }}'
      engineVersion: v2
      type: Opaque
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: diode-hydra-secret
  namespace: netbox
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: diode
      secretKey: db_password
    - remoteRef:
        key: diode
        property: hydra_secrets_system
      secretKey: hydra_secrets_system
    - remoteRef:
        key: diode
        property: hydra_secrets_cookie
      secretKey: hydra_secrets_cookie
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: diode-hydra-secret
    template:
      data:
        dsn: postgres://diode:{{ .db_password | urlquery }}@postgresql-default-rw.databases.svc.cluster.local:5432/diode?sslmode=disable
        secretsCookie: '{{ .hydra_secrets_cookie }}'
        secretsSystem: '{{ .hydra_secrets_system }}'
      engineVersion: v2
      type: Opaque
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: diode-auth-oauth2-secret
  namespace: netbox
spec:
  data:
    - remoteRef:
        key: diode
        property: diode_ingest_client_secret
      secretKey: diode_ingest_client_secret
    - remoteRef:
        key: diode
        property: diode_to_netbox_client_secret
      secretKey: diode_to_netbox_client_secret
    - remoteRef:
        key: diode
        property: netbox_to_diode_client_secret
      secretKey: netbox_to_diode_client_secret
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: diode-auth-oauth2-secret
    template:
      data:
        client-credentials.json: |
          [
            {
              "client_id": "diode-ingest",
              "client_secret": "{{ .diode_ingest_client_secret }}",
              "grant_types": ["client_credentials"],
              "scope": "diode:ingest"
            },
            {
              "client_id": "diode-to-netbox",
              "client_secret": "{{ .diode_to_netbox_client_secret }}",
              "grant_types": ["client_credentials"],
              "scope": "netbox:read netbox:write"
            },
            {
              "client_id": "netbox-to-diode",
              "client_secret": "{{ .netbox_to_diode_client_secret }}",
              "grant_types": ["client_credentials"],
              "scope": "diode:read diode:write"
            }
          ]
      engineVersion: v2
      type: Opaque
