apiVersion: v1
kind: Service
metadata:
  labels:
    app: diode
    app.kubernetes.io/name: diode
  name: diode-gateway
  namespace: netbox
spec:
  externalName: envoy-envoy-gateway-system-envoy-gateway-dc2b3bc0.envoy-gateway-system.svc.cluster.local
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  type: ExternalName
