apiVersion: v1
kind: Service
metadata:
  labels:
    app: diode
    app.kubernetes.io/name: diode
  name: diode-reconciler-h2c
  namespace: netbox
spec:
  ports:
    - appProtocol: kubernetes.io/h2c
      name: grpc
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: diode-reconciler
  type: ClusterIP
