apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hubble-oauth2-proxy-secret-5a9307
spec:
  data:
    - remoteRef:
        key: hubble-oauth2-proxy
        property: client_id
      secretKey: client-id
    - remoteRef:
        key: hubble-oauth2-proxy
        property: client_secret
      secretKey: client-secret
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: hubble-oauth2-proxy-secret-5a9307
    template:
      engineVersion: v2
      type: Opaque
