apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arc-secret
  namespace: arc-runners
spec:
  data:
    - remoteRef:
        key: github-arc
        property: github_app_id
      secretKey: github_app_id
    - remoteRef:
        key: github-arc
        property: github_app_installation_id
      secretKey: github_app_installation_id
    - remoteRef:
        key: github-arc
        property: github_app_private_key
      secretKey: github_app_private_key
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: arc-secret
    template:
      engineVersion: v2
      type: Opaque
