apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-app-secret
  namespace: arc-runners
spec:
  data:
    - remoteRef:
        key: sharc-rusk
        property: github_app_id
      secretKey: github_app_id
    - remoteRef:
        key: sharc-rusk
        property: github_app_installation_id
      secretKey: github_app_installation_id
    - remoteRef:
        key: sharc-rusk
        property: github_app_private_key
      secretKey: github_app_private_key
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: github-app-secret
    template:
      data:
        github_app_id: '{{ .github_app_id }}'
        github_app_installation_id: '{{ .github_app_installation_id }}'
        github_app_private_key: '{{ .github_app_private_key }}'
      engineVersion: v2
      type: Opaque
