rbac:
  pspEnabled: false

image:
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 80m
    memory: 400Mi
  limits:
    memory: 600Mi

tolerations:
- operator: Exists

victoria-metrics-single:
  enabled: false

grafana:
  enabled: false
