apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://get.pinniped.dev/v0.47.0/install-pinniped-supervisor.yaml
  - https://get.pinniped.dev/v0.47.0/install-pinniped-concierge-crds.yaml
  - https://get.pinniped.dev/v0.47.0/install-pinniped-concierge-resources.yaml
