apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ac-hacking-2024-back-249275
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: ac_hacking
      secretKey: postgres_password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ac-hacking-2024-back-249275
