apiVersion: v1
kind: Service
metadata:
  labels:
    app: ac-hacking-2024-back
    app.kubernetes.io/name: ac-hacking-2024-back
  name: ac-hacking-2024-back
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: ac-hacking-2024-back
    app.kubernetes.io/name: ac-hacking-2024-back
  type: ClusterIP
