replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 150Mi
  limits:
    cpu: 1
    memory: 1Gi

config:
  # logVerbosity defines the logging level. Valid values are as follows:
  # -2: Errors only
  # -1: Errors and warnings
  #  0: Errors, warnings, and information
  #  number greater than 0: Errors, warnings, information, and debug details.
  logVerbosity: "0"

podMonitor:
  enabled: true
