kubeProxyReplacement: true
k8sServicePort: 6443
bgpControlPlane:
  enabled: true
k8sClientRateLimit:
  qps: 10
  burst: 20
resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    memory: 2Gi
envoy:
  resources:
    requests:
      cpu: 10m
      memory: 51Mi
operator:
  replicas: 1
  resources:
    requests:
      cpu: 10m
      memory: 60Mi
    limits:
      memory: 512Mi
