fullnameOverride: argocd-agent

agentMode: managed
logFormat: json
server: argocd-agent.local.walnuts.dev
destinationBasedMapping: true
createNamespace: true
allowedNamespaces: "*"
labelSelector: "argocd-agent=true"

serviceMonitor:
  enabled: true

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
