apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: http-dump
  namespace: default
spec:
  rules:
    - hosts:
        - httptest.walnuts.dev
  scalingMetric:
    concurrency:
      targetValue: 10
  target:
    port: 8080
    service: http-dump
