apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: penpot-secrets
  namespace: penpot
spec:
  data:
    - remoteRef:
        key: terraform-external-secrets
        property: penpot-client-id
      secretKey: oidcClientID
    - remoteRef:
        key: terraform-external-secrets
        property: penpot-client-secret
      secretKey: oidcClientSecret
    - remoteRef:
        key: terraform-external-secrets
        property: penpot-oidc-required-role
      secretKey: oidcRequiredRole
    - remoteRef:
        key: terraform-external-secrets
        property: penpot-api-secret-key
      secretKey: apiSecretKey
    - remoteRef:
        key: terraform-external-secrets
        property: penpot-database-password
      secretKey: databasePassword
    - remoteRef:
        key: terraform-external-secrets
        property: penpot-redis-password
      secretKey: redisPassword
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: penpot-secrets
    template:
      data:
        api-secret-key: '{{ .apiSecretKey }}'
        database-uri: postgresql://postgresql-default-rw.databases.svc.cluster.local:5432/penpot
        oidc-client-id: '{{ .oidcClientID }}'
        oidc-client-secret: '{{ .oidcClientSecret }}'
        oidc-required-role: '{{ .oidcRequiredRole }}'
        password: '{{ .databasePassword }}'
        redis-password: '{{ .redisPassword }}'
        redis-uri: redis://:{{ .redisPassword }}@penpot-valkey.penpot.svc.cluster.local:6379/0
        username: penpot
      engineVersion: v2
      type: Opaque
