apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oekaki-dengon-game-secret-e57a8a
spec:
  data:
    - remoteRef:
        key: terraform-external-secrets
        property: oekaki-client-id
      secretKey: client-id
    - remoteRef:
        key: terraform-external-secrets
        property: oekaki-client-secret
      secretKey: client-secret
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: oekaki-dengon-game-secret-e57a8a
    template:
      engineVersion: v2
      type: Opaque
