apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oekaki-dengon-game-secret-ed8d10
spec:
  data:
    - remoteRef:
        key: oekaki-dengon-game
        property: client_id
      secretKey: client-id
    - remoteRef:
        key: oekaki-dengon-game
        property: client_secret
      secretKey: client-secret
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: oekaki-dengon-game-secret-ed8d10
    template:
      engineVersion: v2
      type: Opaque
