config:
  enableDirectDownloads: true
  cacheCleanupOlderThanDays: 30
  storage:
    driver: s3
    s3:
      bucket: gha-cache
      region: us-east-1
      endpointUrl: https://seaweedfs.local.walnuts.dev
  db:
    driver: postgres
    postgres:
      host: postgresql-default-rw.databases.svc.cluster.local
      port: 5432
      user: gha_cache_server
      database: gha_cache_server

serviceAccount:
  name: gha-cache-server

extraEnv:
- name: DB_POSTGRES_PASSWORD
  valueFrom:
    secretKeyRef:
      name: gha-cache-server
      key: db_password
- name: AWS_WEB_IDENTITY_TOKEN_FILE
  value: /var/run/secrets/sts.seaweedfs.com/serviceaccount/token
- name: AWS_ROLE_ARN
  value: arn:aws:iam::role/gha-cache-server
- name: AWS_ENDPOINT_URL_STS
  value: https://seaweedfs.local.walnuts.dev
- name: AWS_ENDPOINT_URL_S3
  value: https://seaweedfs.local.walnuts.dev
- name: S3_USE_PATH_STYLE
  value: "true"

extraVolumes:
- name: seaweedfs-sts-token
  projected:
    sources:
    - serviceAccountToken:
        audience: sts.seaweedfs.com
        expirationSeconds: 86400
        path: token

extraVolumeMounts:
- name: seaweedfs-sts-token
  mountPath: /var/run/secrets/sts.seaweedfs.com/serviceaccount
  readOnly: true

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: "1"
    memory: 2Gi
