[seaweedfs-default]
type = s3
provider = SeaweedFS
env_auth = true
region = us-east-1
profile = seaweedfs-default

[seaweedfs-biscuit]
type = s3
provider = SeaweedFS
env_auth = true
region = ap-northeast-1
profile = seaweedfs-biscuit
upload_cutoff = 16M
