[seaweedfs-default]
type = s3
provider = SeaweedFS
env_auth = true
region = us-east-1
profile = seaweedfs-default

[seaweedfs-biscuit]
type = s3
provider = SeaweedFS
env_auth = true
region = ap-northeast-1
profile = seaweedfs-biscuit
upload_cutoff = 16M

[b2]
type = s3
provider = Other
env_auth = true
region = us-west-004
endpoint = https://s3.us-west-004.backblazeb2.com
profile = b2
upload_cutoff = 16M
