apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: github-readme-stats
  namespace: github-readme-stats
spec:
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s:k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
          rules:
            dns:
              - matchName: api.github.com.github-readme-stats.svc.cluster.local
              - matchName: api.github.com.svc.cluster.local
              - matchName: api.github.com.cluster.local
              - matchName: api.github.com
    - toFQDNs:
        - matchName: api.github.com
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
  endpointSelector:
    matchLabels:
      k8s:app: github-readme-stats
      k8s:app.kubernetes.io/name: github-readme-stats
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:app.kubernetes.io/component: proxy
            k8s:app.kubernetes.io/managed-by: envoy-gateway
            k8s:app.kubernetes.io/name: envoy
            k8s:io.kubernetes.pod.namespace: envoy-gateway-system
      toPorts:
        - ports:
            - port: "9000"
              protocol: TCP
