apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: github-readme-stats-422e93
spec:
    data:
        - remoteRef:
            key: github_token
            property: github-readme-stats
          secretKey: github-token
    refreshInterval: 1m
    secretStoreRef:
        kind: ClusterSecretStore
        name: onepassword
    target:
        name: github-readme-stats-422e93

---
