headlamp:
  enabled: true
  service_name: headlamp
  cert_name: headlamp-tls
  config:
    enableHelm: true
    watchPlugins: true
  pluginsManager:
    enabled: true
    configContent: |
      plugins:
      - name: cert-manager
        source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_cert-manager
        version: 0.1.1
      - name: keda
        source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_keda
        version: 0.1.2
      installOptions:
        parallel: true
        maxConcurrent: 2
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 512Mi
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 512Mi

oidc:
  client_id_is_secret: true
  issuer: https://auth.walnuts.dev
  user_in_idtoken: true
  domain: ""
  scopes: openid email profile urn:zitadel:iam:org:project:id:385225927988084784:aud
  claims:
    sub: sub
    email: email
    given_name: given_name
    family_name: family_name
    display_name: name
    groups: my:zitadel:grants

services:
  enable_tokenrequest: true
  token_request_audience: https://kubernetes.default.svc.cluster.local
  token_request_expiration_seconds: 600
  node_selectors: {}
  tolerations: []
  resources:
    requests:
      cpu: 10m
      memory: 1Gi
    limits:
      memory: 2Gi

openunison:
  replicas: 1
  auto_timestamp: false
  force_update: initial-openunison-deployment
  non_secret_data:
    K8S_DB_SSO: oidc
    SHOW_PORTAL_ORGS: "false"
  secrets: []
  enable_provisioning: false
  use_standard_jit_workflow: true
  az_groups:
  - 385225927988084784:cluster-admin
  groups:
    areJson: "false"
