apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: picca-video-transcode-worker
  namespace: picca
spec:
  maxReplicaCount: 8
  minReplicaCount: 1
  scaleTargetRef:
    name: picca-video-transcode-worker
  triggers:
    - authenticationRef:
        name: picca-rabbitmq-worker-auth
      metadata:
        mode: ExpectedQueueConsumptionTime
        protocol: http
        queueName: picca.video-transcode
        value: "300"
      metricType: Value
      type: rabbitmq
