apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radar-auth
spec:
  data:
    - remoteRef:
        key: terraform-external-secrets
        property: radar-auth-secret
      secretKey: auth-secret
    - remoteRef:
        key: terraform-external-secrets
        property: radar-client-secret
      secretKey: client-secret
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: radar-auth
    template:
      engineVersion: v2
      type: Opaque
