apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: radar
  namespace: radar
spec:
  rules:
    - hosts:
        - k8s-dashboard.walnuts.dev
  scalingMetric:
    concurrency:
      targetValue: 10
  target:
    port: 9280
    service: radar
