apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: radar
  namespace: radar
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: envoy-gateway-system
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: keda
      ports:
        - port: 9280
          protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: radar
      app.kubernetes.io/name: radar
  policyTypes:
    - Ingress
