apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-agent-kurumi
  namespace: argocd
  labels:
    argocd-agent: "true"
spec:
  project: kurumi
  destination:
    name: kurumi
    namespace: argocd
  sources:
  - repoURL: https://github.com/walnuts1018/infra
    targetRevision: clusterapi
    ref: infra
  - repoURL: https://github.com/argoproj-labs/argocd-agent
    targetRevision: v0.9.0
    path: install/helm-repo/argocd-agent-agent
    helm:
      valueFiles:
      - $infra/k8s/_argocd/agent/agent/values.yaml
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - ServerSideApply=true
    - FailOnSharedResource=true
