apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-kurumi
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  goTemplate: true
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/walnuts1018/infra
          revision: clusterapi
          files:
          - path: "k8s/apps/*/app.json5"
      - list:
          elements:
          - kurumiEnabled: '{{ hasKey .clusters "kurumi" }}'
    selector:
      matchLabels:
        kurumiEnabled: "true"
  ignoreApplicationDifferences:
  - jsonPointers:
    - /spec/syncPolicy
  template:
    metadata:
      name: '{{ printf "%s-kurumi" .name }}'
    spec:
      project: default
      destination:
        name: kurumi
        namespace: '{{.namespace}}'
      sources:
      - repoURL: 'https://github.com/walnuts1018/infra'
        targetRevision: clusterapi
        path: '{{.path.path}}'
        directory:
          recurse: true
          exclude: '{config/*,_*/*}'
          jsonnet:
            tlas:
            {{- range $tla := .clusters.kurumi.jsonnet.tlas }}
            - {{ $tla | toJson }}
            {{- end }}
        ref: infra
      {{- with .additionalSources.helm }}
      - repoURL: '{{ .repoURL }}'
        chart: '{{ .chart }}'
        targetRevision: '{{ .targetRevision }}'
        helm:
          releaseName: '{{ $.name }}'
          valueFiles:
          {{- range .valueFiles }}
          - {{ printf "$infra/%s/%s" $.path.path . }}
          {{- end }}
          {{- with $.clusters.kurumi.additionalSources.helm.additionalValueFiles }}
          {{- range . }}
          - {{ printf "$infra/%s/%s" $.path.path . }}
          {{- end }}
          {{- end }}
      {{- end }}
      {{- range .additionalSources.kustomize }}
      - repoURL: '{{ .repoURL }}'
        path: '{{ .path }}'
        targetRevision: '{{ .targetRevision }}'
        {{- with .patches }}
        kustomize:
          patches: {{ . | toJson }}
        {{- end }}
      {{- end }}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
        - ServerSideApply=true
        - FailOnSharedResource=true
  templatePatch: |
    {{- with  .annotations }}
    metadata:
      annotations:
        {{- range $key, $value := . }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    {{- end }}
