apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces-kurumi
  namespace: argocd
spec:
  project: default
  destination:
    name: kurumi
  source:
    path: k8s/namespaces
    repoURL: 'https://github.com/walnuts1018/infra'
    targetRevision: main
    directory:
      recurse: true
      exclude: '{config/*,_*/*}'
      jsonnet: {}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - ServerSideApply=true
    - FailOnSharedResource=true
