apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: n8n
    app.kubernetes.io/name: n8n
  name: n8n
  namespace: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
      app.kubernetes.io/name: n8n
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: n8n
        app.kubernetes.io/name: n8n
    spec:
      containers:
        - args:
            - -c
            - n8n start
          command:
            - /bin/sh
          env:
            - name: DB_TYPE
              value: postgresdb
            - name: DB_POSTGRESDB_HOST
              value: postgresql-default.databases.svc.cluster.local
            - name: DB_POSTGRESDB_PORT
              value: "5432"
            - name: DB_POSTGRESDB_DATABASE
              value: n8n
            - name: DB_POSTGRESDB_USER
              value: n8n
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres-password
                  name: n8n-51bef9
            - name: N8N_PROTOCOL
              value: http
            - name: N8N_PORT
              value: "5678"
          image: n8nio/n8n:1.104.1
          name: n8n
          ports:
            - containerPort: 5678
          resources:
            limits:
              memory: 500Mi
            requests:
              memory: 250Mi
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - all
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /home/node/.n8n
              name: data
            - mountPath: /home/node/.cache
              name: cache
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: n8n
        - emptyDir: {}
          name: cache
