apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-51bef9
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: n8n
      secretKey: postgres-password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: n8n-51bef9
