apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-5a87c3
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: n8n
      secretKey: postgres-password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: n8n-5a87c3
    template:
      engineVersion: v2
      type: Opaque
