apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: n8n
    app.kubernetes.io/name: n8n
  name: n8n
  namespace: n8n
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
