apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: opentelemetry-collectors-d974ce
spec:
  data:
    - remoteRef:
        key: mackerel
        property: api-key
      secretKey: mackerel-api-key
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: opentelemetry-collectors-d974ce
