apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  labels:
    app: walnuk-backend
    app.kubernetes.io/name: walnuk-backend
  name: walnuk-backend
  namespace: walnuk
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: apiserver
        controlledResources:
          - memory
        maxAllowed:
          cpu: 500m
          memory: 256Mi
        minAllowed:
          cpu: 5m
          memory: 10Mi
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: walnuk-backend
  updatePolicy:
    updateMode: Auto
