apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-daemonset-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-daemonset-collector
subjects:
  - kind: ServiceAccount
    name: otel-daemonset-collector
    namespace: opentelemetry-collector
