apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: iwashi-0528a0
  namespace: iwashi-system
spec:
  data:
    - remoteRef:
        key: terraform-external-secrets
        property: iwashi-client-id
      secretKey: client_id
    - remoteRef:
        key: terraform-external-secrets
        property: iwashi-client-secret
      secretKey: client_secret
    - remoteRef:
        key: terraform-external-secrets
        property: iwashi-database-password
      secretKey: database_password
    - remoteRef:
        key: terraform-external-secrets
        property: iwashi-session-key
      secretKey: session_key
    - remoteRef:
        key: terraform-external-secrets
        property: iwashi-discovery-key
      secretKey: discovery_key
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: iwashi-0528a0
    template:
      data:
        ATLAS_DATABASE_URL: postgres://iwashi:{{ .database_password }}@postgresql-default-rw.databases.svc.cluster.local:5432/iwashi?sslmode=require
        DATABASE_URL: postgres://iwashi:{{ .database_password }}@postgresql-default-rw.databases.svc.cluster.local:5432/iwashi?sslmode=require&pool_max_conns=2
        DISCOVERY_KEY: '{{ .discovery_key }}'
        OIDC_CLIENT_ID: '{{ .client_id }}'
        OIDC_CLIENT_SECRET: '{{ .client_secret }}'
        SESSION_KEY: '{{ .session_key }}'
      engineVersion: v2
      type: Opaque
