manager:
  replicas: 1

  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi

  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: 'kubernetes.io/hostname'
    whenUnsatisfiable: 'ScheduleAnyway'
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: clickhouse-operator
        app.kubernetes.io/instance: clickhouse-operator

certManager:
  enabled: true

metrics:
  enabled: true

prometheus:
  # ServiceMonitorを有効化
  enabled: true
