apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: iwashi-collector-discovery-8f6730
  namespace: iwashi-system
spec:
  data:
    - remoteRef:
        key: terraform-external-secrets
        property: iwashi-discovery-key
      secretKey: discovery_key
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: iwashi-collector-discovery-8f6730
    template:
      data:
        DISCOVERY_KEY: '{{ .discovery_key }}'
      engineVersion: v2
      type: Opaque
