apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: scylla-cluster-users-fd1b5f
  namespace: databases
spec:
  data:
    - remoteRef:
        key: scylladb
        property: admin
      secretKey: admin_password
    - remoteRef:
        key: scylladb
        property: walnuk
      secretKey: walnuk_password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: scylla-cluster-users-fd1b5f
    template:
      data:
        admin_password: '{{ .admin_password }}'
        admin_username: cassandra
        users.json: |
          [
            {
              "username": "walnuk",
              "password": "{{ .walnuk_password }}",
              "superuser": false,
              "login": true,
              "keyspace_permissions": [
                "walnuk"
              ]
            }
          ]
      engineVersion: v2
      type: Opaque
