apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: scylla-cluster-migrations-b4e797
  namespace: databases
spec:
  data:
    - remoteRef:
        key: scylladb
        property: admin
      secretKey: admin_password
    - remoteRef:
        key: scylladb
        property: walnuk
      secretKey: walnuk_password
    - remoteRef:
        key: scylladb
        property: prfexample
      secretKey: prfexample_password
    - remoteRef:
        key: scylladb
        property: picca
      secretKey: picca_password
    - remoteRef:
        key: scylladb
        property: picca_dev
      secretKey: picca_dev_password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: scylla-cluster-migrations-b4e797
    template:
      data:
        admin_password: '{{ .admin_password }}'
        admin_username: cassandra
        migrations.cql: |
          CREATE KEYSPACE IF NOT EXISTS walnuk
              WITH replication = {'class': 'NetworkTopologyStrategy', 'iwakura': '3'}
              AND tablets = {'enabled': false};
          CREATE ROLE IF NOT EXISTS 'walnuk'
              WITH PASSWORD = '{{ .walnuk_password }}'
              AND SUPERUSER = false
              AND LOGIN = true;
          GRANT ALL PERMISSIONS ON KEYSPACE walnuk TO 'walnuk';


          CREATE KEYSPACE IF NOT EXISTS picca
              WITH replication = {'class': 'NetworkTopologyStrategy', 'iwakura': '3'}
              AND tablets = {'enabled': false};
          CREATE ROLE IF NOT EXISTS 'picca'
              WITH PASSWORD = '{{ .picca_password }}'
              AND SUPERUSER = false
              AND LOGIN = true;
          GRANT ALL PERMISSIONS ON KEYSPACE picca TO 'picca';

          CREATE KEYSPACE IF NOT EXISTS picca_dev
              WITH replication = {'class': 'NetworkTopologyStrategy', 'iwakura': '3'}
              AND tablets = {'enabled': false};
          CREATE ROLE IF NOT EXISTS 'picca_dev'
              WITH PASSWORD = '{{ .picca_dev_password }}'
              AND SUPERUSER = false
              AND LOGIN = true;
          GRANT ALL PERMISSIONS ON KEYSPACE picca_dev TO 'picca_dev';

          CREATE KEYSPACE IF NOT EXISTS prfexample
              WITH replication = {'class': 'NetworkTopologyStrategy', 'iwakura': '3'}
              AND tablets = {'enabled': false};
          CREATE ROLE IF NOT EXISTS 'prfexample'
              WITH PASSWORD = '{{ .prfexample_password }}'
              AND SUPERUSER = false
              AND LOGIN = true;
          GRANT ALL PERMISSIONS ON KEYSPACE prfexample TO 'prfexample';
      engineVersion: v2
      type: Opaque
