apiVersion: v1
kind: Service
metadata:
    labels:
        app: kibana
        app.kubernetes.io/name: kibana
    name: kibana
    namespace: elasticsearch
spec:
    ports:
        - name: http
          port: 5601
          targetPort: 5601
    selector:
        app: kibana
        app.kubernetes.io/name: kibana
    type: ClusterIP

---
