vmselect:
  enabled: true
  mode: deployment
  replicaCount: 1
  horizontalPodAutoscaler:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 100
          type: Utilization
      type: Resource
  resources:
    requests:
      cpu: 10m
      memory: 60Mi
    limits:
      memory: 512Gi
  serviceMonitor:
    enabled: true

vminsert:
  enabled: true
  mode: deployment
  replicaCount: 1
  horizontalPodAutoscaler:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 100
          type: Utilization
      type: Resource
  resources:
    requests:
      cpu: 80m
      memory: 250Mi
    limits:
      memory: 1Gi
  serviceMonitor:
    enabled: true

vmstorage:
  enabled: true
  replicaCount: 1
  retentionPeriod: 1y
  persistentVolume:
    enabled: true
    storageClassName: "topolvm-hdd"
    size: 128Gi
  resources:
    requests:
      cpu: 100m
      memory: 1.5Gi
    limits:
      memory: 2Gi
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: 'kubernetes.io/hostname'
    whenUnsatisfiable: 'ScheduleAnyway'
    labelSelector:
      matchLabels:
        app: vmstorage
        app.kubernetes.io/instance: victoria-metrics
        app.kubernetes.io/name: victoria-metrics-cluster
  serviceMonitor:
    enabled: true
