apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineHealthCheck
metadata:
  name: longhorn-backup-validate-worker
  namespace: longhorn-backup-validate
spec:
  clusterName: longhorn-backup-validate
  nodeStartupTimeout: 10m
  selector:
    matchLabels:
      cluster.x-k8s.io/deployment-name: longhorn-backup-validate-worker
  unhealthyConditions:
    - status: Unknown
      timeout: 300s
      type: Ready
    - status: "False"
      timeout: 300s
      type: Ready
