apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: esp32-thermohygrometer-exporter-db2bfc
spec:
  data:
    - remoteRef:
        key: esp32_thermohygrometer_exporter
        property: device_url
      secretKey: device_url
    - remoteRef:
        key: esp32_thermohygrometer_exporter
        property: private_key_json
      secretKey: private_key_json
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: esp32-thermohygrometer-exporter-db2bfc
    template:
      engineVersion: v2
      type: Opaque
