apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-oauth2-proxy-secret-fa68e9
spec:
  data:
    - remoteRef:
        key: terraform-external-secrets
        property: longhorn-client-id
      secretKey: client-id
    - remoteRef:
        key: terraform-external-secrets
        property: longhorn-client-secret
      secretKey: client-secret
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: longhorn-oauth2-proxy-secret-fa68e9
    template:
      engineVersion: v2
      type: Opaque
