apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-oauth2-proxy-secret-76c292
spec:
  data:
    - remoteRef:
        key: longhorn-oauth2-proxy
        property: client_secret
      secretKey: client-secret
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: longhorn-oauth2-proxy-secret-76c292
    template:
      engineVersion: v2
      type: Opaque
