apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coder-oidc
  namespace: coder
spec:
  data:
    - remoteRef:
        key: terraform-external-secrets
        property: coder-client-id
      secretKey: client-id
    - remoteRef:
        key: terraform-external-secrets
        property: coder-client-secret
      secretKey: client-secret
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: coder-oidc
    template:
      engineVersion: v2
      type: Opaque
