apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coder-github
  namespace: coder
spec:
  data:
    - remoteRef:
        key: coder
        property: github-client-id
      secretKey: client-id
    - remoteRef:
        key: coder
        property: github-client-secret
      secretKey: client-secret
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: coder-github
    template:
      engineVersion: v2
      type: Opaque
