apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coder-db-url
  namespace: coder
spec:
  data:
    - remoteRef:
        key: terraform-external-secrets
        property: coder-database-password
      secretKey: database_password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: coder-db-url
    template:
      data:
        url: postgres://coder:{{ .database_password }}@postgresql-default-rw.databases.svc.cluster.local:5432/coder?sslmode=require
      engineVersion: v2
      type: Opaque
