apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  labels:
    app: openchokin-back
    app.kubernetes.io/name: openchokin-back
  name: openchokin-back
  namespace: openchokin
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: openchokin-back
        controlledResources:
          - memory
        maxAllowed:
          cpu: 500m
          memory: 128Mi
        minAllowed:
          cpu: 1m
          memory: 10Mi
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: openchokin-back
  updatePolicy:
    updateMode: Auto
