apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: akvorado-snmp-b9ac04
  namespace: akvorado
spec:
  data:
    - remoteRef:
        key: snmp
        property: community
      secretKey: snmp_community
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: akvorado-snmp-b9ac04
    template:
      data:
        snmp.yaml: |
          - type: snmp
            credentials:
              ::/0:
                communities:
                  - "{{ .snmp_community }}"
      engineVersion: v2
      type: Opaque
