apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: akvorado-secret-f7c651
spec:
  data:
    - remoteRef:
        key: akvorado
        property: client_secret
      secretKey: client-secret
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: akvorado-secret-f7c651
    template:
      engineVersion: v2
      type: Opaque
