apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: akvorado-secret-b88a29
spec:
  data:
    - remoteRef:
        key: terraform-external-secrets
        property: akvorado-client-id
      secretKey: client-id
    - remoteRef:
        key: terraform-external-secrets
        property: akvorado-client-secret
      secretKey: client-secret
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: akvorado-secret-b88a29
    template:
      engineVersion: v2
      type: Opaque
