msgTopologyOperator:
  enabled: false

clusterOperator:
  watchAllNamespaces: true
  networkPolicy:
    extraIngress:
    - ports:
      - port: 9443
        protocol: TCP
  resources:
    requests:
      cpu: 5m
      memory: 48Mi
    limits:
      memory: 512Mi
  tolerations:
  - key: "node.walnuts.dev/low-performance"
    operator: "Exists"
