apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headlamp-oidc
spec:
  data:
    - remoteRef:
        key: terraform-external-secrets
        property: headlamp-client-id
      secretKey: OIDC_CLIENT_ID
    - remoteRef:
        key: terraform-external-secrets
        property: headlamp-client-secret
      secretKey: OIDC_CLIENT_SECRET
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: headlamp-oidc
    template:
      data:
        OIDC_CALLBACK_URL: https://headlamp.walnuts.dev/oidc-callback
        OIDC_CLIENT_ID: '{{ .OIDC_CLIENT_ID }}'
        OIDC_CLIENT_SECRET: '{{ .OIDC_CLIENT_SECRET }}'
        OIDC_ISSUER_URL: https://auth.walnuts.dev
        OIDC_SCOPES: openid,email,profile,urn:zitadel:iam:org:project:id:385225927988084784:aud
        OIDC_USE_ACCESS_TOKEN: "false"
        OIDC_USE_PKCE: "true"
        config: |
          apiVersion: v1
          kind: Config
          clusters:
          - name: main
            cluster:
              server: https://kube-oidc-proxy.kube-oidc-proxy.svc:443
              certificate-authority: /etc/kube-oidc-proxy/trust-bundle.pem
          contexts:
          - name: main
            context:
              cluster: main
              user: oidc
          current-context: main
          users:
          - name: oidc
            user:
              auth-provider:
                name: oidc
                config:
                  idp-issuer-url: "https://auth.walnuts.dev"
                  client-id: "{{ .OIDC_CLIENT_ID }}"
                  client-secret: "{{ .OIDC_CLIENT_SECRET }}"
      engineVersion: v2
      type: Opaque
