apiVersion: v1
kind: Service
metadata:
  labels:
    headlamp-prometheus: "true"
  name: prometheus-k8s
  namespace: headlamp
spec:
  ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: headlamp-prometheus-proxy
