apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: stalwart
  namespace: stalwart
spec:
  nodeSets:
    - config:
        node.store.allow_mmap: false
      count: 1
      name: default
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                limits:
                  cpu: "1"
                  memory: 2Gi
                requests:
                  cpu: 250m
                  memory: 1Gi
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 4Gi
            storageClassName: longhorn
  version: 9.4.2
  volumeClaimDeletePolicy: DeleteOnScaledownOnly
