apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stalwart-c92609
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: stalwart
      secretKey: postgres_password
    - remoteRef:
        key: seaweedfs
        property: stalwart_secretkey
      secretKey: s3_secret_access_key
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: stalwart-c92609
    template:
      data:
        postgres_password: '{{ .postgres_password }}'
        s3_access_key: stalwart
        s3_secret_access_key: '{{ .s3_secret_access_key }}'
      engineVersion: v2
      type: Opaque
