apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stalwart-c268e3
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: stalwart
      secretKey: postgres_password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: stalwart-c268e3
    template:
      data:
        postgres_password: '{{ .postgres_password }}'
      engineVersion: v2
      type: Opaque
