apiVersion: moco.cybozu.com/v1beta2
kind: MySQLCluster
metadata:
  labels:
    app: mysql-default
    app.kubernetes.io/name: mysql-default
  name: mysql-default
spec:
  podTemplate:
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
              weight: 100
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - mysql
                topologyKey: kubernetes.io/hostname
              weight: 10
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - test
              topologyKey: kubernetes.io/hostname
      containers:
        - image: ghcr.io/cybozu-go/moco/mysql:8.4.4
          name: mysqld
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 400Mi
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - all
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
  primaryServiceTemplate:
    spec:
      loadBalancerIP: 192.168.0.133
      type: LoadBalancer
  replicas: 3
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: longhorn
