apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres.default.credentials.postgresql.acid.zalan.do
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: postgres
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: postgres.default.credentials.postgresql.acid.zalan.do
    template:
      data:
        password: '{{ .password }}'
        username: postgres
      engineVersion: v2
      metadata:
        labels:
          application: spilo
          cluster-name: default
          team: default
      type: Opaque
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: juglans.default.credentials.postgresql.acid.zalan.do
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: juglans
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: juglans.default.credentials.postgresql.acid.zalan.do
    template:
      data:
        password: '{{ .password }}'
        username: juglans
      engineVersion: v2
      metadata:
        labels:
          application: spilo
          cluster-name: default
          team: default
      type: Opaque
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fitbit-manager.default.credentials.postgresql.acid.zalan.do
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: fitbit_manager
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: fitbit-manager.default.credentials.postgresql.acid.zalan.do
    template:
      data:
        password: '{{ .password }}'
        username: fitbit_manager
      engineVersion: v2
      metadata:
        labels:
          application: spilo
          cluster-name: default
          team: default
      type: Opaque
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana.default.credentials.postgresql.acid.zalan.do
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: grafana
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: grafana.default.credentials.postgresql.acid.zalan.do
    template:
      data:
        password: '{{ .password }}'
        username: grafana
      engineVersion: v2
      metadata:
        labels:
          application: spilo
          cluster-name: default
          team: default
      type: Opaque
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hedgedoc.default.credentials.postgresql.acid.zalan.do
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: hedgedoc
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: hedgedoc.default.credentials.postgresql.acid.zalan.do
    template:
      data:
        password: '{{ .password }}'
        username: hedgedoc
      engineVersion: v2
      metadata:
        labels:
          application: spilo
          cluster-name: default
          team: default
      type: Opaque
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: misskey.default.credentials.postgresql.acid.zalan.do
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: misskey
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: misskey.default.credentials.postgresql.acid.zalan.do
    template:
      data:
        password: '{{ .password }}'
        username: misskey
      engineVersion: v2
      metadata:
        labels:
          application: spilo
          cluster-name: default
          team: default
      type: Opaque
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud.default.credentials.postgresql.acid.zalan.do
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: nextcloud
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: nextcloud.default.credentials.postgresql.acid.zalan.do
    template:
      data:
        password: '{{ .password }}'
        username: nextcloud
      engineVersion: v2
      metadata:
        labels:
          application: spilo
          cluster-name: default
          team: default
      type: Opaque
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oekaki-dengon-game.default.credentials.postgresql.acid.zalan.do
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: oekaki_dengon_game
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: oekaki-dengon-game.default.credentials.postgresql.acid.zalan.do
    template:
      data:
        password: '{{ .password }}'
        username: oekaki_dengon_game
      engineVersion: v2
      metadata:
        labels:
          application: spilo
          cluster-name: default
          team: default
      type: Opaque
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openchokin.default.credentials.postgresql.acid.zalan.do
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: openchokin
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: openchokin.default.credentials.postgresql.acid.zalan.do
    template:
      data:
        password: '{{ .password }}'
        username: openchokin
      engineVersion: v2
      metadata:
        labels:
          application: spilo
          cluster-name: default
          team: default
      type: Opaque
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wakatime.default.credentials.postgresql.acid.zalan.do
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: wakatime
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: wakatime.default.credentials.postgresql.acid.zalan.do
    template:
      data:
        password: '{{ .password }}'
        username: wakatime
      engineVersion: v2
      metadata:
        labels:
          application: spilo
          cluster-name: default
          team: default
      type: Opaque
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zitadel.default.credentials.postgresql.acid.zalan.do
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: zitadel
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: zitadel.default.credentials.postgresql.acid.zalan.do
    template:
      data:
        password: '{{ .password }}'
        username: zitadel
      engineVersion: v2
      metadata:
        labels:
          application: spilo
          cluster-name: default
          team: default
      type: Opaque
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ac-hacking.default.credentials.postgresql.acid.zalan.do
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: ac_hacking
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ac-hacking.default.credentials.postgresql.acid.zalan.do
    template:
      data:
        password: '{{ .password }}'
        username: ac_hacking
      engineVersion: v2
      metadata:
        labels:
          application: spilo
          cluster-name: default
          team: default
      type: Opaque
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mucaron.default.credentials.postgresql.acid.zalan.do
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: mucaron
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mucaron.default.credentials.postgresql.acid.zalan.do
    template:
      data:
        password: '{{ .password }}'
        username: mucaron
      engineVersion: v2
      metadata:
        labels:
          application: spilo
          cluster-name: default
          team: default
      type: Opaque
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: affine.default.credentials.postgresql.acid.zalan.do
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: affine
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: affine.default.credentials.postgresql.acid.zalan.do
    template:
      data:
        password: '{{ .password }}'
        username: affine
      engineVersion: v2
      metadata:
        labels:
          application: spilo
          cluster-name: default
          team: default
      type: Opaque
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclarity.default.credentials.postgresql.acid.zalan.do
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: openclarity
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: openclarity.default.credentials.postgresql.acid.zalan.do
    template:
      data:
        password: '{{ .password }}'
        username: openclarity
      engineVersion: v2
      metadata:
        labels:
          application: spilo
          cluster-name: default
          team: default
      type: Opaque
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n.default.credentials.postgresql.acid.zalan.do
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: n8n
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: n8n.default.credentials.postgresql.acid.zalan.do
    template:
      data:
        password: '{{ .password }}'
        username: n8n
      engineVersion: v2
      metadata:
        labels:
          application: spilo
          cluster-name: default
          team: default
      type: Opaque
