apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox
spec:
  data:
    - remoteRef:
        key: netbox
        property: superuser-password
      secretKey: superuser_password
    - remoteRef:
        key: netbox
        property: superuser-api-token
      secretKey: superuser_api_token
    - remoteRef:
        key: netbox
        property: secret_key
      secretKey: secret_key
    - remoteRef:
        key: netbox
        property: api_token_peppers
      secretKey: api_token_peppers1
    - remoteRef:
        key: postgres_passwords
        property: netbox
      secretKey: db_password
    - remoteRef:
        key: resend
        property: api-key
      secretKey: smtp_password
    - remoteRef:
        key: netbox
        property: valkey_password
      secretKey: valkey_password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: netbox
    template:
      data:
        api_token: '{{ .superuser_api_token }}'
        api_token_peppers: '{"1": "{{ .api_token_peppers1 }}"}'
        db-password: '{{ .db_password }}'
        email: netbox-admin@walnuts.dev
        password: '{{ .superuser_password }}'
        secret_key: '{{ .secret_key }}'
        smtp-password: '{{ .smtp_password }}'
        username: netbox-admin
        valkey_password: '{{ .valkey_password }}'
      engineVersion: v2
      type: Opaque
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-oidc-config
spec:
  data:
    - remoteRef:
        key: netbox
        property: oidc-client-id
      secretKey: client_id
    - remoteRef:
        key: netbox
        property: oidc-client-secret
      secretKey: client_secret
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: netbox-oidc-config
    template:
      data:
        oidc.py: |
          SOCIAL_AUTH_OIDC_KEY = '{{ .client_id }}'
          SOCIAL_AUTH_OIDC_SECRET = '{{ .client_secret }}'
          SOCIAL_AUTH_OIDC_OIDC_ENDPOINT = 'https://auth.walnuts.dev'
      engineVersion: v2
      type: Opaque
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-diode-config
spec:
  data:
    - remoteRef:
        key: diode
        property: netbox_to_diode_client_secret
      secretKey: netbox_to_diode_client_secret
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: netbox-diode-config
    template:
      data:
        diode.yaml: |
          PLUGINS_CONFIG:
            netbox_diode_plugin:
              netbox_to_diode_client_secret: "{{ .netbox_to_diode_client_secret }}"
      engineVersion: v2
      type: Opaque
