---
# Source: gha-runner-scale-set/templates/no_permission_serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: 98e96cb4d328154cc69e3c5d9c737180-gha-rs-no-permission
  namespace: gha-runner
  labels:
    helm.sh/chart: gha-rs-0.10.1
    app.kubernetes.io/name: 98e96cb4d328154cc69e3c5d9c737180
    app.kubernetes.io/instance: 98e96cb4d328154cc69e3c5d9c737180
    app.kubernetes.io/version: "0.10.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: 98e96cb4d328154cc69e3c5d9c737180
    actions.github.com/scale-set-namespace: gha-runner
  finalizers:
    - actions.github.com/cleanup-protection
---
# Source: gha-runner-scale-set/templates/manager_role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: 98e96cb4d328154cc69e3c5d9c737180-gha-rs-manager
  namespace: gha-runner
  labels:
    helm.sh/chart: gha-rs-0.10.1
    app.kubernetes.io/name: 98e96cb4d328154cc69e3c5d9c737180
    app.kubernetes.io/instance: 98e96cb4d328154cc69e3c5d9c737180
    app.kubernetes.io/version: "0.10.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: 98e96cb4d328154cc69e3c5d9c737180
    actions.github.com/scale-set-namespace: gha-runner
    app.kubernetes.io/component: manager-role
  finalizers:
    - actions.github.com/cleanup-protection
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - patch
  - update
---
# Source: gha-runner-scale-set/templates/manager_role_binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: 98e96cb4d328154cc69e3c5d9c737180-gha-rs-manager
  namespace: gha-runner
  labels:
    helm.sh/chart: gha-rs-0.10.1
    app.kubernetes.io/name: 98e96cb4d328154cc69e3c5d9c737180
    app.kubernetes.io/instance: 98e96cb4d328154cc69e3c5d9c737180
    app.kubernetes.io/version: "0.10.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: 98e96cb4d328154cc69e3c5d9c737180
    actions.github.com/scale-set-namespace: gha-runner
    app.kubernetes.io/component: manager-role-binding
  finalizers:
    - actions.github.com/cleanup-protection
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 98e96cb4d328154cc69e3c5d9c737180-gha-rs-manager
subjects:
- kind: ServiceAccount
  name: 
    gha-runner-controller-gha-rs-controller
  namespace: 
    gha-runner-controller
---
# Source: gha-runner-scale-set/templates/autoscalingrunnerset.yaml
apiVersion: actions.github.com/v1alpha1
kind: AutoscalingRunnerSet
metadata:
  name: 98e96cb4d328154cc69e3c5d9c737180
  namespace: gha-runner
  labels:
    app.kubernetes.io/component: "autoscaling-runner-set"
    helm.sh/chart: gha-rs-0.10.1
    app.kubernetes.io/name: 98e96cb4d328154cc69e3c5d9c737180
    app.kubernetes.io/instance: 98e96cb4d328154cc69e3c5d9c737180
    app.kubernetes.io/version: "0.10.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: 98e96cb4d328154cc69e3c5d9c737180
    actions.github.com/scale-set-namespace: gha-runner
  annotations:
    actions.github.com/values-hash: 4d9369c3f5c1019975692b7c5400b6648783f74e276fa3fab0e204414a54418
    actions.github.com/cleanup-manager-role-binding: 98e96cb4d328154cc69e3c5d9c737180-gha-rs-manager
    actions.github.com/cleanup-manager-role-name: 98e96cb4d328154cc69e3c5d9c737180-gha-rs-manager
    actions.github.com/cleanup-no-permission-service-account-name: 98e96cb4d328154cc69e3c5d9c737180-gha-rs-no-permission
spec:
  githubConfigUrl: https://github.com/walnuts1018/cloudflare-tunnel-operator
  githubConfigSecret: gha-runner

  template:
    spec:
      restartPolicy: Never
      serviceAccountName: 98e96cb4d328154cc69e3c5d9c737180-gha-rs-no-permission
      initContainers:
      - name: init-dind-externals
        
        image: ghcr.io/actions/actions-runner:latest
        command: ["cp"]
        args: ["-r", "-v", "/home/runner/externals/.", "/home/runner/tmpDir/"]
        volumeMounts:
          - name: dind-externals
            mountPath: /home/runner/tmpDir
      containers:
      - name: runner
        
        command: 
          - /home/runner/run.sh
        image: 
          ghcr.io/actions/actions-runner:latest
        env:
          - name: DOCKER_HOST
            value: unix:///var/run/docker.sock
          - name: RUNNER_WAIT_FOR_DOCKER_IN_SECONDS
            value: "120"
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
          - name: dind-sock
            mountPath: /var/run
      - name: dind
        image: docker:dind
        args:
          - dockerd
          - --host=unix:///var/run/docker.sock
          - --group=$(DOCKER_GROUP_GID)
        env:
          - name: DOCKER_GROUP_GID
            value: "123"
        securityContext:
          privileged: true
        volumeMounts:
          - name: work
            mountPath: /home/runner/_work
          - name: dind-sock
            mountPath: /var/run
          - name: dind-externals
            mountPath: /home/runner/externals
      
      volumes:
      - name: dind-sock
        emptyDir: {}
      - name: dind-externals
        emptyDir: {}
      
      - name: work
        emptyDir: {}
