---
# Source: prometheus-blackbox-exporter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: iwashi-blackbox-prometheus-blackbox-exporter
  namespace: iwashi-blackbox
  labels:
    helm.sh/chart: prometheus-blackbox-exporter-11.18.0
    app.kubernetes.io/name: prometheus-blackbox-exporter
    app.kubernetes.io/instance: iwashi-blackbox
    app.kubernetes.io/version: "v0.28.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: prometheus-blackbox-exporter/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: iwashi-blackbox-prometheus-blackbox-exporter
  namespace: iwashi-blackbox
  labels:
    helm.sh/chart: prometheus-blackbox-exporter-11.18.0
    app.kubernetes.io/name: prometheus-blackbox-exporter
    app.kubernetes.io/instance: iwashi-blackbox
    app.kubernetes.io/version: "v0.28.0"
    app.kubernetes.io/managed-by: Helm
data:
  blackbox.yaml: |
    modules:
      http_2xx:
        http:
          follow_redirects: true
          preferred_ip_protocol: ip4
          valid_http_versions:
          - HTTP/1.1
          - HTTP/2.0
        prober: http
        timeout: 5s
---
# Source: prometheus-blackbox-exporter/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: iwashi-blackbox-prometheus-blackbox-exporter
  namespace: iwashi-blackbox
  labels:
    helm.sh/chart: prometheus-blackbox-exporter-11.18.0
    app.kubernetes.io/name: prometheus-blackbox-exporter
    app.kubernetes.io/instance: iwashi-blackbox
    app.kubernetes.io/version: "v0.28.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 9115
      targetPort: http
      protocol: TCP
      name: http
    
  selector:
    app.kubernetes.io/name: prometheus-blackbox-exporter
    app.kubernetes.io/instance: iwashi-blackbox
---
# Source: prometheus-blackbox-exporter/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iwashi-blackbox-prometheus-blackbox-exporter
  namespace: iwashi-blackbox
  labels:
    helm.sh/chart: prometheus-blackbox-exporter-11.18.0
    app.kubernetes.io/name: prometheus-blackbox-exporter
    app.kubernetes.io/instance: iwashi-blackbox
    app.kubernetes.io/version: "v0.28.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-blackbox-exporter
      app.kubernetes.io/instance: iwashi-blackbox
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        helm.sh/chart: prometheus-blackbox-exporter-11.18.0
        app.kubernetes.io/name: prometheus-blackbox-exporter
        app.kubernetes.io/instance: iwashi-blackbox
        app.kubernetes.io/version: "v0.28.0"
        app.kubernetes.io/managed-by: Helm
      annotations:
        checksum/config: f43e733459690a84886aec93596a01748c2f936776a534eeaeb9f084e62ebb91
    spec:
      automountServiceAccountToken: false
      serviceAccountName: iwashi-blackbox-prometheus-blackbox-exporter
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      
      containers:
      
      - name: blackbox-exporter
        image: quay.io/prometheus/blackbox-exporter:v0.28.0
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
        args:
        - "--config.file=/config/blackbox.yaml"
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: 2m
            memory: 39Mi
        ports:
        - containerPort: 9115
          name: http
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/healthy
            port: http
        readinessProbe:
          httpGet:
            path: /-/healthy
            port: http
        volumeMounts:
        - mountPath: /config
          name: config
      hostNetwork: false
      volumes:
      - name: config
        configMap:
          name: iwashi-blackbox-prometheus-blackbox-exporter
