apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-ddns-config
spec:
  secretStoreRef:
    name: vault-secretstore
    kind: ClusterSecretStore
  refreshInterval: 1m
  target:
    name: cloudflare-ddns-config
    template:
      engineVersion: v2
      type: Opaque
      templateFrom:
      - target: Data
        configMap:
          name: cloudflare-ddns-config-base
          items:
          - key: config.json
            templateAs: Values
  data:
  - secretKey: config.
    remoteRef:
      key: cloudflare
      property: k8s-tunnel-token
