apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  labels:
    app: openchokin-front
    app.kubernetes.io/name: openchokin-front
  name: openchokin-front
  namespace: openchokin
spec:
  maxReplicaCount: 2
  minReplicaCount: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: openchokin-front
  triggers:
    - metadata:
        value: "95"
      metricType: Utilization
      type: cpu
