replicaCount: 1

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    memory: 512Mi

webhook:
  enabled: true
  certManager:
    enabled: true

otel:
  metricsExporter: otlp
  serviceName: sharc
  exporter:
    endpoint: http://default-collector.opentelemetry-collector.svc.cluster.local:4318
    protocol: http/protobuf
