# Scylla Manager log level, allowed values are: error, warn, info, debug, trace
logLevel: info
image:
  tag: 3.10.1@sha256:8e02f5f3501ecbc5286acb09a9fed854bc621e422eba48b71159382604d6491a
resources:
  requests:
    cpu: 10m
    memory: 20Mi
serviceAccount:
  create: true
  name: ""
scylla:
  developerMode: true
  scyllaImage:
    tag: 2025.4.10
  agentImage:
    tag: 3.10.1@sha256:aa85a3da293d0e5ca29214a575efe79b352d6678343d2f6d9aee711ac339f903
  datacenter: iwakura
  racks:
  - name: iwakura-a
    members: 1
    storage:
      capacity: 5Gi
      storageClassName: local-path
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 1
        memory: 1Gi
    placement:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: storage.walnuts.dev/slow
              operator: DoesNotExist
      tolerations: []
serviceMonitor:
  create: true
