# Scylla Manager log level, allowed values are: error, warn, info, debug, trace
logLevel: info
image:
  tag: 3.12.1@sha256:3ec70ef48c31bae76472a1422c64946782b884c36aa3fad0ce69791c47a26370
resources:
  requests:
    cpu: 10m
    memory: 20Mi
serviceAccount:
  create: true
  name: ""
scylla:
  developerMode: true
  scyllaImage:
    tag: 2025.4.10
  agentImage:
    tag: 3.12.1@sha256:b04eedb439652d1c949dead49de4837cf3f2a3656c8ecc5f574c340556da7673
  datacenter: iwakura
  racks:
  - name: iwakura-a
    members: 1
    storage:
      capacity: 5Gi
      storageClassName: local-path
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 1
        memory: 1Gi
    placement:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: storage.walnuts.dev/slow
              operator: DoesNotExist
      tolerations: []
serviceMonitor:
  create: true
