recommender:
  enabled: true
  replicas: 1
  extraArgs:
  - "--pod-recommendation-min-memory-mb=10"
  resources:
    requests:
      cpu: 50m
      memory: 500Mi
    limits:
      memory: 1000Mi

updater:
  enabled: false
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 500Mi
    limits:
      memory: 1000Mi
