policies:
  nexus_inventory_nxos:
    config:
      defaults:
        site: "home"
        role: "switch"
        tags: [ "netbox-discovery", "device-discovery", "nxos" ]
        device:
          comments: "Discovered by NetBox Device Discovery"
      options:
        discovery_drivers: [ "nxos" ]
    scope:
    - driver: nxos
      hostname: "192.168.0.4"
      username: "${NAPALM_USERNAME}"
      password: "${NAPALM_PASSWORD}"
      # optional_args:
      #   enable_password: "${NAPALM_ENABLE_PASSWORD}"
