apiVersion: v1
data:
  Corefile: |
    (base) {
        errors
        log
        loop
        loadbalance
        reload
        ready
        cache
    }

    . {
        import base
        health {
            lameduck 5s
        }
        prometheus :9153
        forward . 1.1.1.1 1.0.0.1 {
            tls_servername cloudflare-dns.com
            force_tcp
        }
    }

    # http://.:443 {
    #     tls /etc/coredns/tls/tls.crt /etc/coredns/tls/tls.key
    #     forward . 127.0.0.1:53
    # }

    # tls://.:853 {
    #     tls /etc/coredns/tls/tls.crt /etc/coredns/tls/tls.key
    #     forward . 127.0.0.1:53
    # }


    local.walnuts.dev {
        import base
        etcd {
            path /skydns
            endpoint http://coredns-etcd.coredns.svc.cluster.local:2379
            fallthrough
        }
        forward . 1.1.1.1 1.0.0.1 {
            tls_servername cloudflare-dns.com
            force_tcp
        }
    }
kind: ConfigMap
metadata:
  labels:
    app: coredns
    app.kubernetes.io/name: coredns
  name: coredns-config-5ffb83
  namespace: coredns
