operator:
  # While you can run more replicas of our operator, only one operator instance will be the leader and serving traffic.
  # You can run multiple replicas, but they will not improve the performance of KEDA, it could only reduce downtime during a failover.
  # Learn more in [our documentation](https://keda.sh/docs/latest/operate/cluster/#high-availability).
  replicaCount: 1

metricsServer:
  # While you can run more replicas of our metric server, only one instance will used and serve traffic.
  # You can run multiple replicas, but they will not improve the performance of KEDA, it could only reduce downtime during a failover.
  # Learn more in [our documentation](https://keda.sh/docs/latest/operate/cluster/#high-availability).
  replicaCount: 1

webhooks:
  replicaCount: 1

logging:
  operator:
    level: info
    format: json
    timeEncoding: rfc3339
    stackTracesEnabled: false
  metricServer:
    zapLevel: info
    zapEncoder: json
    zapTimeEncoding: rfc3339
  webhooks:
    level: info
    format: json
    timeEncoding: rfc3339

resources:
  operator:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 1
      memory: 1000Mi
  metricServer:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 1
      memory: 1000Mi
  webhooks:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 1
      memory: 1000Mi

topologySpreadConstraints:
  operator:
  - maxSkew: 1
    topologyKey: 'kubernetes.io/hostname'
    whenUnsatisfiable: 'ScheduleAnyway'
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: keda-operator
        app.kubernetes.io/instance: keda-operator
  metricsServer:
  - maxSkew: 1
    topologyKey: 'kubernetes.io/hostname'
    whenUnsatisfiable: 'ScheduleAnyway'
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: keda-operator-metrics-apiserver
        app.kubernetes.io/instance: keda-operator
  webhooks:
  - maxSkew: 1
    topologyKey: 'kubernetes.io/hostname'
    whenUnsatisfiable: 'ScheduleAnyway'
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: keda-admission-webhooks
        app.kubernetes.io/instance: keda-operator

prometheus:
  metricServer:
    enabled: true
    serviceMonitor:
      enabled: true
    podMonitor:
      enabled: true
  operator:
    enabled: true
    serviceMonitor:
      enabled: true
    podMonitor:
      enabled: true
  webhooks:
    enabled: true
    serviceMonitor:
      enabled: true

# -- Enable service links in pods. Although enabled, mirroring k8s default, it is highly recommended to disable,
# due to its legacy status [Legacy container links](https://docs.docker.com/engine/network/links/)
enableServiceLinks: false
