apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ipu-953c75
spec:
  data:
    - remoteRef:
        key: terraform-external-secrets
        property: ipu-client-id
      secretKey: client-id
    - remoteRef:
        key: terraform-external-secrets
        property: ipu-client-secret
      secretKey: client-secret
    - remoteRef:
        key: ipu-oauth2-proxy
        property: cookie-secret
      secretKey: session-secret
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ipu-953c75
    template:
      engineVersion: v2
      type: Opaque
