apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ipu
  namespace: ipu
spec:
  hostnames:
    - ipu.walnuts.dev
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway-system
  rules:
    - backendRefs:
        - kind: Service
          name: ipu
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
