apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: ipu
  namespace: ipu
spec:
  rules:
    - hosts:
        - ipu.walnuts.dev
  scalingMetric:
    concurrency:
      targetValue: 10
  target:
    port: 8080
    service: ipu
