apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ipu
  namespace: ipu
spec:
  cooldownPeriod: 300
  maxReplicaCount: 3
  minReplicaCount: 0
  scaleTargetRef:
    name: ipu
  triggers:
    - metadata:
        interceptorRoute: ipu
        scalerAddress: keda-add-ons-http-external-scaler.keda:9090
      type: external-push
