apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: kurumi-api-server
  namespace: shutdown-manager
spec:
  targetRefs:
    - group: gateway.envoyproxy.io
      kind: Backend
      name: kurumi-api-server
      sectionName: "16443"
  validation:
    caCertificateRefs:
      - group: ""
        kind: ConfigMap
        name: kurumi-ca-5415a6
    hostname: kubernetes.default.svc.cluster.local
