useLegacy: false

cert-manager:
  enabled: false

scheduler:
  enabled: false

webhook:
  certManager: true
  # Storage Capacity Trackingを使うので不要
  podMutatingWebhook:
    enabled: false

lvmd:
  managed: true
  additionalConfigs: []
  #     spare-gb: 10
  #     default: true
  #     lvcreate-options:
  #     - --alloc=normal

controller:
  replicaCount: 1
  podDisruptionBudget:
    enabled: true

node:
  lvmdEmbedded: false
  kubeletWorkDirectory: /var/lib/kubelet

# TODO: PVレベルでバックアップが必要になったら有効化する
snapshot:
  enabled: false

resources:
  topolvm_node:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 128Mi
  csi_registrar:
    requests:
      cpu: 5m
      memory: 16Mi
    limits:
      memory: 64Mi
  liveness_probe:
    requests:
      cpu: 2m
      memory: 8Mi
    limits:
      memory: 32Mi
  topolvm_controller:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 128Mi
  csi_provisioner:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 128Mi
  csi_resizer:
    requests:
      cpu: 5m
      memory: 16Mi
    limits:
      memory: 64Mi
  csi_snapshotter:
    requests:
      cpu: 5m
      memory: 16Mi
    limits:
      memory: 64Mi
  lvmd:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 128Mi
