apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-discovery
  namespace: netbox
spec:
  data:
    - remoteRef:
        key: diode
        property: diode_ingest_client_secret
      secretKey: diode_ingest_client_secret
    - remoteRef:
        key: netbox_discovery
        property: snmp_community
      secretKey: snmp_community
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: netbox-discovery
    template:
      data:
        DIODE_CLIENT_ID: diode-ingest
        DIODE_CLIENT_SECRET: '{{ .diode_ingest_client_secret }}'
        SNMP_COMMUNITY: '{{ .snmp_community }}'
      engineVersion: v2
      type: Opaque
