apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns
spec:
  data:
    - remoteRef:
        key: external-dns
        property: cloudflare_api_token
      secretKey: cloudflare_api_token
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: external-dns
    template:
      engineVersion: v2
      type: Opaque
