apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: external-dns-9eb41d
spec:
    data:
        - remoteRef:
            key: cloudflare
            property: apitoken
          secretKey: cf-api-token
    refreshInterval: 1m
    secretStoreRef:
        kind: ClusterSecretStore
        name: onepassword
    target:
        name: external-dns-9eb41d

---
