resources:
  requests:
    cpu: 2m
    memory: 51Mi
  limits:
    memory: 1Gi
topologySpreadConstraints:
- maxSkew: 1
  topologyKey: 'kubernetes.io/hostname'
  whenUnsatisfiable: 'ScheduleAnyway'
  labelSelector:
    matchLabels:
      app.kubernetes.io/name: external-dns
serviceMonitor:
  enabled: true
triggerLoopOnEvent: true
sources:
- gateway-httproute
- gateway-tlsroute
- gateway-tcproute
- gateway-udproute
policy: upsert-only
registry: txt
excludeDomains:
- "local.walnuts.dev"

provider:
  name: cloudflare
env:
- name: CF_API_TOKEN
  valueFrom:
    secretKeyRef:
      name: envoy-gateway
      key: cloudflare_api_token
