apiVersion: v1
data:
  elasticsearch-plugins.yml: |
    # https://www.elastic.co/guide/en/elasticsearch/plugins/current/manage-plugins-using-configuration-file.html
    plugins:
    - id: analysis-icu
kind: ConfigMap
metadata:
  labels:
    app: elasticsearch
    app.kubernetes.io/name: elasticsearch
  name: elasticsearch-3795d7
  namespace: elasticsearch
