apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    labels:
        app: elasticsearch
        app.kubernetes.io/name: elasticsearch
        recurring-job-group.longhorn.io/default: enabled
    name: elasticsearch
    namespace: elasticsearch
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    storageClassName: longhorn
    volumeName: elasticsearch

---
