apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: kubelet-metrics-proxy
    app.kubernetes.io/name: kubernetes-control-plane-metrics
  name: kubelet-metrics-proxy
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: kubelet-metrics-proxy
  template:
    metadata:
      labels:
        app: kubelet-metrics-proxy
        app.kubernetes.io/name: kubernetes-control-plane-metrics
    spec:
      containers:
        - args:
            - -d
            - -d
            - TCP-LISTEN:11050,fork,reuseaddr,bind=0.0.0.0
            - TCP:127.0.0.1:10250
          image: docker.io/alpine/socat:1.8.1.3@sha256:82ad20f6f6e29b91ff33b6662d24063522b1378f08fd8569cd3ab412cac13f50
          name: kubelet
          ports:
            - containerPort: 11050
              hostPort: 11050
              name: https-metrics
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 3m
              memory: 8Mi
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      tolerations:
        - operator: Exists
