apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-etcd-metrics-proxy
    app.kubernetes.io/name: kubernetes-control-plane-metrics
    jobLabel: kube-etcd
  name: kube-etcd-metrics-proxy
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 12381
      targetPort: 12381
  selector:
    app: kubernetes-control-plane-metrics-proxy
