apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-controller-manager-metrics-proxy
    app.kubernetes.io/name: kubernetes-control-plane-metrics
    jobLabel: kube-controller-manager
  name: kube-controller-manager-metrics-proxy
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 11057
      targetPort: 11057
  selector:
    app: kubernetes-control-plane-metrics-proxy
