apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubernetes-control-plane-metrics
    app.kubernetes.io/name: kubelet-metrics-proxy
    k8s-app: kubelet
  name: kubelet-metrics-proxy
  namespace: kube-system
spec:
  clusterIP: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: https-metrics
      port: 11050
      targetPort: 11050
  selector:
    app: kubelet-metrics-proxy
