apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubernetes-control-plane-metrics-targetallocator-secret-reader
  namespace: monitoring
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
