apiVersion: v1
data:
  rclone.conf: |
    [seaweedmaps]
    type = s3
    provider = Other
    env_auth = true
    endpoint = http://seaweedfs-default-filer.seaweedfs.svc.cluster.local:8333
    region = us-east-1
    no_check_bucket = true
immutable: true
kind: ConfigMap
metadata:
  labels:
    app: maps-update
    app.kubernetes.io/name: maps-update
  name: maps-rclone-config-29db02
  namespace: maps
