apiVersion: v1
kind: Service
metadata:
  name: vyos-collector-ingest
spec:
  loadBalancerIP: 192.168.0.136
  ports:
    - name: syslog-udp
      port: 514
      protocol: UDP
      targetPort: 5514
    - name: netflow-udp
      port: 2055
      protocol: UDP
      targetPort: 2055
  selector:
    app.kubernetes.io/component: opentelemetry-collector
    app.kubernetes.io/instance: opentelemetry-collector.vyos
    app.kubernetes.io/part-of: opentelemetry
  type: LoadBalancer
