fullnameOverride: argocd-agent

principal:
  listen:
    host: ""
  log:
    format: json
  tls:
    clientCert:
      require: true
      matchSubject: true
  auth: "mtls:CN=([^,]+)"
  destinationBasedMapping: true
  labelSelector: "argocd-agent=true"

serviceMonitor:
  enabled: true

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
