apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: hedgedoc-f39c33
spec:
    data:
        - remoteRef:
            key: postgres_passwords
            property: hedgedoc
          secretKey: dbpassword
        - remoteRef:
            key: hedgedoc
            property: client-secret
          secretKey: clientsecret
        - remoteRef:
            key: hedgedoc
            property: minio-access-key
          secretKey: minioaccesskey
        - remoteRef:
            key: hedgedoc
            property: minio-secret-key
          secretKey: miniosecretkey
        - remoteRef:
            key: hedgedoc
            property: session-secret
          secretKey: sessionsecret
    refreshInterval: 1m
    secretStoreRef:
        kind: ClusterSecretStore
        name: onepassword
    target:
        name: hedgedoc-f39c33
        template:
            data:
                client-secret: '{{ .clientsecret }}'
                db-url: postgres://hedgedoc:{{ .dbpassword }}@postgresql-default.databases.svc.cluster.local/hedgedoc
                minio-access-key: '{{ .minioaccesskey }}'
                minio-secret-key: '{{ .miniosecretkey }}'
                session-secret: '{{ .sessionsecret }}'
            engineVersion: v2
            type: Opaque

---
