apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: iwashi-smtp-relay
  namespace: iwashi-system
spec:
  data:
    - remoteRef:
        key: resend
        property: api-key
      secretKey: smtp_password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: iwashi-smtp-relay
    template:
      engineVersion: v2
      type: Opaque
