apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: iwashi-smtp-relay-helm
  namespace: argocd
spec:
  destination:
    namespace: iwashi-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: mail
    helm:
      releaseName: iwashi-smtp-relay
      values: |
        replicaCount: 1

        image:
          repository: boky/postfix
          tag: "5.1.0@sha256:aafc772384232497bed875e1eb66b4d3e54ba1ebc86e2e185a6dc1dbc48182ef"
          pullPolicy: IfNotPresent

        service:
          type: ClusterIP
          port: 587

        dns:
          options:
            - name: ndots
              value: "1"

        headlessService:
          enabled: true

        recreateOnRedeploy: false

        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 256Mi

        config:
          general:
            ALLOWED_SENDER_DOMAINS: resend.walnuts.dev
            RELAYHOST: "[smtp.resend.com]:587"
            RELAYHOST_USERNAME: resend
            RELAYHOST_PASSWORD_FILE: /var/run/secrets/iwashi/smtp/smtp_password
          postfix:
            mynetworks: 127.0.0.0/8,10.0.0.0/8
            smtp_tls_security_level: encrypt

        persistence:
          enabled: true
          accessModes:
            - ReadWriteOnce
          size: 1Gi

        extraVolumes:
          - name: smtp-credentials
            secret:
              secretName: iwashi-smtp-relay
              defaultMode: 0440

        extraVolumeMounts:
          - name: smtp-credentials
            mountPath: /var/run/secrets/iwashi/smtp
            readOnly: true

        serviceAccount:
          create: false
          name: iwashi-smtp-relay
    repoURL: https://bokysan.github.io/docker-postfix
    targetRevision: 5.1.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - FailOnSharedResource=true
