worker_processes auto;
pid /tmp/nginx.pid;

events {
  worker_connections 1024;
}

http {
  access_log /dev/stdout;
  error_log /dev/stderr notice;

  client_body_temp_path /tmp/client_body;
  proxy_temp_path /tmp/proxy;
  fastcgi_temp_path /tmp/fastcgi;
  uwsgi_temp_path /tmp/uwsgi;
  scgi_temp_path /tmp/scgi;

  server {
    listen 9090;

    location = /healthz {
      access_log off;
      return 200;
    }

    location / {
      proxy_pass http://victoria-metrics-victoria-metrics-cluster-vmselect.victoria-metrics.svc.cluster.local:8481/select/0/prometheus/;
      proxy_buffering off;
      proxy_connect_timeout 5s;
      proxy_read_timeout 60s;
    }
  }
}
