replicaCount: 1
useUnprivilegedImage: true

env:
  - name: QDRANT__STORAGE__PERFORMANCE__IO_URING
    value: auto
  - name: QDRANT__STORAGE__OPTIMIZERS__MAX_OPTIMIZATION_THREADS
    value: "1"

readinessProbe:
  enabled: true

livenessProbe:
  enabled: true

resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: "2"
    memory: 8Gi

persistence:
  size: 10Gi
  storageClassName: longhorn

snapshotPersistence:
  enabled: true
  size: 10Gi
  storageClassName: longhorn

metrics:
  serviceMonitor:
    enabled: true
