apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: terrakube-redis-1dc0ec
  namespace: terrakube
spec:
  data:
    - remoteRef:
        key: terrakube
        property: redis_password
      secretKey: redispassword
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: terrakube-redis-1dc0ec
    template:
      engineVersion: v2
      type: Opaque
