apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: terrakube-registry-secrets-overlay-2e7ede
  namespace: terrakube
spec:
  data:
    - remoteRef:
        key: terrakube
        property: pat_secret
      secretKey: patSecret
    - remoteRef:
        key: terrakube
        property: internal_secret
      secretKey: internalSecret
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: terrakube-registry-secrets-overlay-2e7ede
    template:
      data:
        InternalSecret: '{{ .internalSecret }}'
        PatSecret: '{{ .patSecret }}'
      engineVersion: v2
      type: Opaque
