apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: terrakube-executor-secrets-overlay-8bff29
  namespace: terrakube
spec:
  data:
    - remoteRef:
        key: terrakube
        property: internal_secret
      secretKey: internalSecret
    - remoteRef:
        key: terrakube
        property: redis_password
      secretKey: redisPassword
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: terrakube-executor-secrets-overlay-8bff29
    template:
      data:
        InternalSecret: '{{ .internalSecret }}'
        TerrakubeRedisPassword: '{{ .redisPassword }}'
      engineVersion: v2
      type: Opaque
