flow:
  inputs:
  - type: udp
    decoder: netflow
    listen: :2055
    workers: 2
  - type: udp
    decoder: sflow
    listen: :6343
    workers: 2
snmp: !include "/etc/akvorado-secrets/snmp.yaml"
routing:
  provider: static
  asns:
    65000: "Home Network"
