http:
  listen: :8080
snmp:
  communities:
    - targets:
        - 192.168.0.1
        - 192.168.4.2
        - 192.168.4.3
        - 192.168.4.4
routing:
  provider: static
  asns:
    65000: "Home Network"
