apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opencost-secret-2bafb3
spec:
  data:
    - remoteRef:
        key: terraform-external-secrets
        property: opencost-client-id
      secretKey: client-id
    - remoteRef:
        key: terraform-external-secrets
        property: opencost-client-secret
      secretKey: client-secret
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: opencost-secret-2bafb3
    template:
      engineVersion: v2
      type: Opaque
