loglevel: info

opencost:
  exporter:
    resources:
      requests:
        cpu: '10m'
        memory: '55Mi'
      limits:
        memory: '1Gi'
    # # Collector DataSource collects cluster data without a dependency on Prometheus
    # # It is recommended that persistence is enabled alongside it to preserve the state
    # # between pod restarts
    # collectorDataSource:
    #   enabled: false
    #   # -- define the interval at which the collector scrapes for data points (10s, 15s, 1m)
    #   scrapeInterval: 30s
    #   # -- The port at which network pods are open to egress
    #   networkPort: 3001
    #   # -- The number of 10m intervals the Collector DataSource should maintain
    #   retentionResolution10m: 36
    #   # -- The number of 1h intervals the Collector DataSource should maintain
    #   retentionResolution1h: 49
    #   # -- The number of 1d intervals the Collector DataSource should maintain
    #   retentionResolution1d: 15

  customPricing:
    enabled: true
    provider: custom
    costModel:
      description: Modified pricing configuration.
      CPU: 0.0483
      spotCPU: 0.0483
      RAM: 0.0039375
      spotRAM: 0.0039375
      GPU: 0.8564
      storage: 0.096
      zoneNetworkEgress: 0.01
      regionNetworkEgress: 0.01
      internetNetworkEgress: 0.114

  metrics:
    serviceMonitor:
      enabled: true

  prometheus:
    internal:
      enabled: false
    external:
      enabled: true
      url: "http://victoria-metrics-victoria-metrics-cluster-vmselect.victoria-metrics.svc.cluster.local:8481/select/0/prometheus"

  ui:
    enabled: true
    modelFqdn: 127.0.0.1:9003
    httpRoute:
      enabled: true
      parentRefs:
      - name: envoy-gateway
        namespace: envoy-gateway-system
      hostnames:
      - opencost.walnuts.dev
    resources:
      requests:
        cpu: 10m
        memory: 55Mi
      limits:
        memory: 1Gi
