installCRDs: true
config:
  featureGates:
    ExperimentalGatewayAPISupport: true
extraArgs:
- --dns01-recursive-nameservers=1.1.1.1:53,1.0.0.1:53
- --dns01-recursive-nameservers-only
prometheus:
  enabled: true
  servicemonitor:
    enabled: true

resources:
  requests:
    cpu: 1m
    memory: 60Mi

webhook:
  resources:
    requests:
      cpu: 1m
      memory: 50Mi

cainjector:
  resources:
    requests:
      cpu: 1m
      memory: 140Mi

tolerations:
- key: "node.walnuts.dev/low-performance"
  operator: "Exists"
