useCertManager: true
watchAllNamespaces: true

resources:
  requests:
    cpu: 5m
    memory: 48Mi
  limits:
    memory: 512Mi

tolerations:
- key: "node.walnuts.dev/low-performance"
  operator: "Exists"
