useCertManager: true
watchAllNamespaces: true

resources:
  requests:
    cpu: 25m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

tolerations:
- key: "node.walnuts.dev/low-performance"
  operator: "Exists"
