local app = import 'app.json5';
{
  apiVersion: 'v1',
  kind: 'ConfigMap',
  metadata: {
    name: app.name + '-config',
    namespace: app.namespace,
  },
  data: {
    PORT: '8080',
    HTTP_ADDR: ':8080',
    APP_ENV: 'production',
    MEDIA_DIR: '/tmp/beast-media',
    LOG_LEVEL: 'info',
    LOG_TYPE: 'json',
    POSTGRES_PORT: '5432',
    POSTGRES_DB: 'beast',
    POSTGRES_SSLMODE: 'verify-full',
    POSTGRES_MAX_OPEN_CONNS: '20',
    POSTGRES_MAX_IDLE_CONNS: '20',
    S3_REGION: 'us-east-1',
    AWS_REGION: 'us-east-1',
    S3_BUCKET: 'beast',
    S3_USE_PATH_STYLE: 'true',
    S3_ENDPOINT: 'http://seaweedfs-default-filer.seaweedfs.svc.cluster.local:8333',
    AWS_ENDPOINT_URL: 'http://seaweedfs-default-filer.seaweedfs.svc.cluster.local:8333',
    AUTH_MODE: 'introspection',
    OIDC_REQUIRED_ROLE: '391616443902329228:beast-user',
    OIDC_ROLE_CLAIM: 'my:zitadel:grants',
    OIDC_INTROSPECTION_URL: 'https://auth.walnuts.dev/oauth/v2/introspect',
    POSTGRES_HOST: 'postgresql-default-rw.databases.svc.cluster.local',
    RABBITMQ_ENCODE_JOB_QUEUE: 'beast.encoder.jobs',
    RABBITMQ_ENCODE_EVENT_QUEUE: 'beast.encoder.events',
    ENCODER_POLL_INTERVAL: '5s',
    ENCODER_WORK_DIR: '/tmp/beast-encoder',
    ENCODER_HLS_SEGMENT_SECONDS: '4',
    FFMPEG_PATH: 'ffmpeg',
    FFPROBE_PATH: 'ffprobe',
  },
}
