apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: beast-postgres
  namespace: beast
spec:
  data:
    - remoteRef:
        key: terraform-external-secrets
        property: beast-database-password
      secretKey: postgres_password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: beast-postgres
    template:
      data:
        DATABASE_URL: postgres://beast:{{ .postgres_password }}@postgresql-default-rw.databases.svc.cluster.local:5432/beast?sslmode=require&pool_max_conns=2
      engineVersion: v2
      type: Opaque
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: beast-rabbitmq
  namespace: beast
spec:
  data:
    - remoteRef:
        key: terraform-external-secrets
        property: beast-rabbitmq-password
      secretKey: rabbitmq_password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: beast-rabbitmq
    template:
      data:
        KEDA_RABBITMQ_HOST: http://beast:{{ .rabbitmq_password }}@default.rabbitmq.svc.cluster.local:15672/beast
        RABBITMQ_URL: amqp://beast:{{ .rabbitmq_password }}@default.rabbitmq.svc.cluster.local:5672/beast
      engineVersion: v2
      type: Opaque
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: beast-rabbitmq-user-credentials
  namespace: beast
spec:
  data:
    - remoteRef:
        key: terraform-external-secrets
        property: beast-rabbitmq-password
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: beast-rabbitmq-user-credentials
    template:
      data:
        password: '{{ .password }}'
        username: beast
      engineVersion: v2
      type: Opaque
---
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: beast
  namespace: beast
spec:
  name: beast
  rabbitmqClusterReference:
    name: default
    namespace: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: beast
  namespace: beast
spec:
  importCredentialsSecret:
    name: beast-rabbitmq-user-credentials
  rabbitmqClusterReference:
    name: default
    namespace: rabbitmq
  tags:
    - monitoring
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: beast
  namespace: beast
spec:
  permissions:
    configure: .*
    read: .*
    write: .*
  rabbitmqClusterReference:
    name: default
    namespace: rabbitmq
  userReference:
    name: beast
  vhost: beast
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: beast-oidc
  namespace: beast
spec:
  data:
    - remoteRef:
        key: terraform-external-secrets
        property: beast-client-id
      secretKey: oidc_client_id
    - remoteRef:
        key: terraform-external-secrets
        property: beast-client-secret
      secretKey: oidc_client_secret
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: beast-oidc
    template:
      data:
        OIDC_CLIENT_ID: '{{ .oidc_client_id }}'
        OIDC_CLIENT_SECRET: '{{ .oidc_client_secret }}'
      engineVersion: v2
      type: Opaque
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: beast-oidc-gateway
  namespace: beast
spec:
  data:
    - remoteRef:
        key: terraform-external-secrets
        property: beast-client-id
      secretKey: client-id
    - remoteRef:
        key: terraform-external-secrets
        property: beast-client-secret
      secretKey: client-secret
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: beast-oidc-gateway
    template:
      engineVersion: v2
      type: Opaque
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: beast-crypto
  namespace: beast
spec:
  data:
    - remoteRef:
        key: terraform-external-secrets
        property: beast-staging-encryption-key
      secretKey: staging_encryption_key
    - remoteRef:
        key: terraform-external-secrets
        property: beast-media-encryption-key
      secretKey: media_encryption_key
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: beast-crypto
    template:
      data:
        MEDIA_ENCRYPTION_KEY: '{{ .media_encryption_key }}'
        STAGING_ENCRYPTION_KEY: '{{ .staging_encryption_key }}'
      engineVersion: v2
      type: Opaque
