apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: beast-frontend-egress
  namespace: beast
spec:
  egress:
    - ports:
        - port: 8080
          protocol: TCP
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: beast
  podSelector:
    matchLabels:
      app.kubernetes.io/name: frontend
  policyTypes:
    - Egress
