schedule: "*/5 * * * *"

deschedulerPolicy:
  # 1回の実行でevectできるのは、1Nodeあたり3Podまでとする
  maxNoOfPodsToEvictPerNode: 3
  metricsProviders:
  - source: KubernetesMetrics
  profiles:
  - name: request-balance
    plugins:
      balance:
        enabled:
        - RemoveDuplicates
        - RemovePodsViolatingTopologySpreadConstraint
        - LowNodeUtilization
      deschedule:
        enabled:
        - RemovePodsViolatingInterPodAntiAffinity
        - RemovePodsViolatingNodeAffinity
        - RemovePodsViolatingNodeTaints
        - RemovePodsHavingTooManyRestarts
    pluginConfig:
    - name: DefaultEvictor
      args:
        nodeFit: true
        namespaceLabelSelector:
          matchExpressions:
          # github actions runnerは除外
          - key: kubernetes.io/metadata.name
            operator: NotIn
            values:
            - arc-runners
        labelSelector:
          matchExpressions:
          # Job系は除外
          - key: batch.kubernetes.io/controller-uid
            operator: DoesNotExist
        podProtections:
          defaultDisabled:
          - PodsWithLocalStorage
          extraEnabled:
          - PodsWithPVC
          config:
            PodsWithPVC:
              # local path provisionerのPodは他のNodeに移動できないので意味なし
              protectedStorageClasses:
              - name: local-path
    - name: RemoveDuplicates
    - name: RemovePodsViolatingTopologySpreadConstraint
      args:
        constraints:
        - DoNotSchedule
        - ScheduleAnyway
    - name: LowNodeUtilization
      args:
        useDeviationThresholds: false
        thresholds:
          cpu: 60
          memory: 70
        targetThresholds:
          cpu: 75
          memory: 80
    - name: RemovePodsViolatingInterPodAntiAffinity
    - name: RemovePodsViolatingNodeAffinity
      args:
        nodeAffinityType:
        - requiredDuringSchedulingIgnoredDuringExecution
    - name: RemovePodsViolatingNodeTaints
    - name: RemovePodsHavingTooManyRestarts
      args:
        podRestartThreshold: 100
        includingInitContainers: true
  - name: actual-usage
    plugins:
      balance:
        enabled:
        - LowNodeUtilization
    pluginConfig:
    - name: DefaultEvictor
      args:
        nodeFit: true
        namespaceLabelSelector:
          matchExpressions:
          # github actions runnerは除外
          - key: kubernetes.io/metadata.name
            operator: NotIn
            values:
            - arc-runners
        labelSelector:
          matchExpressions:
          # Job系は除外
          - key: batch.kubernetes.io/controller-uid
            operator: DoesNotExist
        podProtections:
          defaultDisabled:
          - PodsWithLocalStorage
          extraEnabled:
          - PodsWithPVC
          config:
            PodsWithPVC:
              protectedStorageClasses:
              - name: local-path
    - name: LowNodeUtilization
      args:
        metricsUtilization:
          source: KubernetesMetrics
        useDeviationThresholds: false
        thresholds:
          cpu: 70
          memory: 70
        targetThresholds:
          cpu: 90
          memory: 90
