serviceMonitor:
  enabled: false
  selfMonitor:
    enabled: false
resources:
  requests:
    cpu: 2m
    memory: 39Mi
  limits:
    memory: 128Mi
securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
