apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: picca-imgproxy-44c96f
  namespace: picca
spec:
  data:
    - remoteRef:
        key: terraform-external-secrets
        property: picca-imgproxy-key
      secretKey: imgproxy_key
    - remoteRef:
        key: terraform-external-secrets
        property: picca-imgproxy-salt
      secretKey: imgproxy_salt
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: picca-imgproxy-44c96f
    template:
      data:
        IMGPROXY_FAIL_ON_DEPRECATION: "true"
        IMGPROXY_KEY: '{{ .imgproxy_key }}'
        IMGPROXY_PROMETHEUS_BIND: :8081
        IMGPROXY_S3_ALLOWED_BUCKETS: picca
        IMGPROXY_S3_ENDPOINT: http://seaweedfs-default-filer.seaweedfs.svc.cluster.local:8333
        IMGPROXY_S3_ENDPOINT_USE_PATH_STYLE: "true"
        IMGPROXY_S3_REGION: us-east-1
        IMGPROXY_SALT: '{{ .imgproxy_salt }}'
        IMGPROXY_TTL: "900"
        IMGPROXY_USE_S3: "true"
      engineVersion: v2
      type: Opaque
