apiVersion: v1
kind: Service
metadata:
  labels:
    app: picca-imgproxy
    app.kubernetes.io/name: picca-imgproxy
  name: picca-imgproxy
  namespace: picca
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: metrics
      port: 8081
      targetPort: 8081
  selector:
    app: picca-imgproxy
    app.kubernetes.io/name: picca-imgproxy
  type: ClusterIP
