apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: samba-secret-a965ee
spec:
  data:
    - remoteRef:
        key: samba
        property: password
      secretKey: account-samba
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: samba-secret-a965ee
