apiVersion: v1
kind: Service
metadata:
  labels:
    app: samba-prober
    app.kubernetes.io/name: samba-prober
  name: samba-prober
  namespace: samba
spec:
  ports:
    - name: metrics
      port: 9187
      protocol: TCP
      targetPort: metrics
  selector:
    app: samba-prober
    app.kubernetes.io/name: samba-prober
  type: ClusterIP
