apiVersion: v1
kind: Service
metadata:
  annotations:
    lbipam.cilium.io/ips: 192.168.12.132
  labels:
    app: samba
    app.kubernetes.io/name: samba
  name: samba
  namespace: samba
spec:
  externalTrafficPolicy: Local
  ports:
    - port: 445
      protocol: TCP
      targetPort: 10445
  selector:
    app: samba
    app.kubernetes.io/name: samba
  type: LoadBalancer
