apiVersion: v1
data:
  blackbox.yml: |
    modules:
      http_pd_leader:
        prober: http
        timeout: 5s
        http:
          method: GET
          valid_status_codes: [200]
          preferred_ip_protocol: ip4
          fail_if_body_not_matches_regexp:
            - '"member_id"\s*:\s*[0-9]+'
            - '"name"\s*:\s*"tikv-cluster-pd-[0-9]+"'
          tls_config:
            ca_file: /etc/pd-client-tls/ca.crt
            cert_file: /etc/pd-client-tls/tls.crt
            key_file: /etc/pd-client-tls/tls.key
            server_name: tikv-cluster-pd-peer.databases.svc.cluster.local
kind: ConfigMap
metadata:
  name: tikv-cluster-pd-leader-prober
  namespace: databases
