apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-targetallocator-tikv-metrics-secrets
  namespace: databases
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-targetallocator-tikv-metrics-secrets
subjects:
  - kind: ServiceAccount
    name: otel-prometheus-targetallocator
    namespace: opentelemetry-collector
