apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-targetallocator-tikv-metrics-secrets
  namespace: databases
rules:
  - apiGroups:
      - ""
    resourceNames:
      - tikv-cluster-pd-cluster-secret
      - tikv-cluster-tikv-cluster-secret
    resources:
      - secrets
    verbs:
      - get
