apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: misskey-ingress
  namespace: misskey
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: envoy-gateway-system
          podSelector:
            matchLabels:
              app.kubernetes.io/component: proxy
              app.kubernetes.io/managed-by: envoy-gateway
              app.kubernetes.io/name: envoy
      ports:
        - port: 3000
          protocol: TCP
  podSelector:
    matchLabels:
      app: misskey
      app.kubernetes.io/name: misskey
  policyTypes:
    - Ingress
