apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: misskey-valkey
    app.kubernetes.io/name: misskey-valkey
  name: misskey-valkey
  namespace: misskey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: misskey-valkey
      app.kubernetes.io/name: misskey-valkey
  serviceName: misskey-valkey-headless
  template:
    metadata:
      labels:
        app: misskey-valkey
        app.kubernetes.io/name: misskey-valkey
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: storage.walnuts.dev/slow
                    operator: DoesNotExist
      containers:
        - args:
            - --maxmemory-policy
            - noeviction
            - --requirepass
            - $(REDIS_PASSWORD)
          command:
            - valkey-server
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redisPassword
                  name: misskey-396dc9
          image: valkey/valkey:9.1.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - valkey-cli -a "$REDIS_PASSWORD" ping
            initialDelaySeconds: 15
            periodSeconds: 10
          name: valkey
          ports:
            - containerPort: 6379
              name: valkey
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - valkey-cli -a "$REDIS_PASSWORD" ping
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 5m
              memory: 16Mi
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - all
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /data
              name: data
      securityContext:
        fsGroup: 999
        fsGroupChangePolicy: OnRootMismatch
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: longhorn
