apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prfexample-803a13
  namespace: prfexample
spec:
  data:
    - remoteRef:
        key: scylladb
        property: prfexample
      secretKey: scylladb_password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: prfexample-803a13
    template:
      data:
        scylladb_password: '{{ .scylladb_password }}'
        scylladb_username: prfexample
      engineVersion: v2
      type: Opaque
