apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  labels:
    app: prfexample
    app.kubernetes.io/name: prfexample
  name: prfexample
  namespace: prfexample
spec:
  maxReplicaCount: 2
  minReplicaCount: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prfexample
  triggers:
    - metadata:
        value: "95"
      metricType: Utilization
      type: cpu
