[leveldb2]
enabled = false

[cassandra2]
enabled = true
keyspace = "seaweedfs"
hosts = ["scylla-cluster-client.databases.svc"]
username = "seaweedfs"
password = "{{ .scylladb_password }}"
ssl_ca_path = "/etc/seaweedfs/scylladb-ca/ca.crt"
ssl_cert_path = "/etc/seaweedfs/scylladb-client/tls.crt"
ssl_key_path = "/etc/seaweedfs/scylladb-client/tls.key"
localDC = "iwakura"

[postgres2.loki_chunks]
enabled = true
location = "/buckets/loki-chunks"
createTable = """
  CREATE TABLE IF NOT EXISTS "%s" (
    dirhash   BIGINT,
    name      VARCHAR(65535),
    directory VARCHAR(65535),
    meta      bytea,
    PRIMARY KEY (dirhash, name)
  );
"""
hostname = "postgresql-default-rw.databases.svc.cluster.local"
port = 5432
username = "seaweedfs"
password = "{{ .postgres_seaweedfs_password }}"
database = "seaweedfs_loki_chunks"
schema = ""
sslmode = "disable"
connection_max_idle = 10
connection_max_open = 50
connection_max_lifetime_seconds = 300
pgbouncer_compatible = false
enableUpsert = true
upsertQuery = """
  INSERT INTO "%[1]s" (dirhash, name, directory, meta)
    VALUES($1, $2, $3, $4)
    ON CONFLICT (dirhash, name) DO UPDATE SET
      directory=EXCLUDED.directory,
      meta=EXCLUDED.meta
"""
