[leveldb2]
enabled = false

[tikv]
enabled = true
pdaddrs = "tikv-cluster-pd.databases.svc.cluster.local:2379"
keyPrefix = "seaweedfs-default/"
ca_path = "/etc/seaweedfs/tikv-client/ca.crt"
cert_path = "/etc/seaweedfs/tikv-client/tls.crt"
key_path = "/etc/seaweedfs/tikv-client/tls.key"
verify_cn = "TiDB"
