[leveldb2]
enabled = false

[cassandra2]
enabled = true
keyspace = "seaweedfs"
hosts = ["scylla-cluster-client.databases.svc"]
username = "seaweedfs"
password = "{{ .scylladb_password }}"
ssl_ca_path = "/etc/seaweedfs/scylladb-ca/ca.crt"
ssl_cert_path = "/etc/seaweedfs/scylladb-client/tls.crt"
ssl_key_path = "/etc/seaweedfs/scylladb-client/tls.key"
localDC = "iwakura"

[postgres2.loki_chunks]
enabled = true
location = "/buckets/loki-chunks"
hostname = "postgresql-default-rw.databases.svc.cluster.local"
port = 5432
database = "seaweedfs_loki_chunks"
username = "seaweedfs"
password = "{{ .postgres_seaweedfs_password }}"
sslmode = "disable"
