apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: komga-9782f5
spec:
    data:
        - remoteRef:
            key: komga
            property: client-secret
          secretKey: clientsecret
    refreshInterval: 1m
    secretStoreRef:
        kind: ClusterSecretStore
        name: onepassword
    target:
        name: komga-9782f5
        template:
            engineVersion: v2
            templateFrom:
                - configMap:
                    items:
                        - key: application.yml
                          templateAs: Values
                    name: komga-secret-template-de46a6
                  target: Data
            type: Opaque

---
