apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shumoku-oidc-54a017
spec:
  data:
    - remoteRef:
        key: terraform-external-secrets
        property: shumoku-client-id
      secretKey: client-id
    - remoteRef:
        key: terraform-external-secrets
        property: shumoku-client-secret
      secretKey: client-secret
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: shumoku-oidc-54a017
    template:
      engineVersion: v2
      type: Opaque
