apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: shumoku
  namespace: netbox
spec:
  rules:
    - hosts:
        - shumoku.walnuts.dev
  scalingMetric:
    concurrency:
      targetValue: 10
  target:
    port: 8080
    service: shumoku
