apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: shumoku
    app.kubernetes.io/name: shumoku
  name: shumoku
  namespace: netbox
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
