apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: shumoku
  namespace: netbox
spec:
  cooldownPeriod: 300
  maxReplicaCount: 1
  minReplicaCount: 0
  scaleTargetRef:
    name: shumoku
  triggers:
    - metadata:
        interceptorRoute: shumoku
        scalerAddress: keda-add-ons-http-external-scaler.keda:9090
      type: external-push
