apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: keda-http-addon-helm
  namespace: argocd
spec:
  destination:
    namespace: keda
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: keda-add-ons-http
    helm:
      releaseName: keda-http-addon
      valuesObject:
        interceptor:
          replicas:
            max: 10
            min: 1
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 64Mi
        operator:
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 64Mi
        scaler:
          replicas: 1
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 64Mi
    repoURL: https://kedacore.github.io/charts
    targetRevision: 0.15.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - FailOnSharedResource=true
