apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ipxe-manager-8b232b
spec:
  data:
    - remoteRef:
        key: ipxe-manager
        property: client-secret
      secretKey: client-secret
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ipxe-manager-8b232b
