apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: visual-regression-tracker-d80b2e
spec:
  data:
    - remoteRef:
        key: terraform-external-secrets
        property: visual-regression-tracker-jwt-secret
      secretKey: jwt_secret
    - remoteRef:
        key: postgres_passwords
        property: visual_regression_tracker
      secretKey: postgres_password
    - remoteRef:
        key: seaweedfs
        property: visual_regression_tracker_secretkey
      secretKey: seaweedfs_secret_key
    - remoteRef:
        key: terraform-external-secrets
        property: visual-regression-tracker-admin-password
      secretKey: admin_password
    - remoteRef:
        key: terraform-external-secrets
        property: visual-regression-tracker-admin-api-key
      secretKey: admin_api_key
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: visual-regression-tracker-d80b2e
    template:
      data:
        AWS_ACCESS_KEY_ID: visual_regression_tracker
        AWS_SECRET_ACCESS_KEY: '{{ .seaweedfs_secret_key }}'
        DATABASE_URL: postgresql://visual_regression_tracker:{{ .postgres_password }}@postgresql-default-rw.databases.svc.cluster.local:5432/visual_regression_tracker?connection_limit=10
        DEFAULT_USER_API_KEY: '{{ .admin_api_key }}'
        DEFAULT_USER_PASSWORD: '{{ .admin_password }}'
        jwt_secret: '{{ .jwt_secret }}'
      engineVersion: v2
      type: Opaque
