apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: visual-regression-tracker-migration
    app.kubernetes.io/name: visual-regression-tracker-migration
  name: visual-regression-tracker-migration-1197c5f7e1
  namespace: visual-regression-tracker
spec:
  template:
    metadata:
      labels:
        app: visual-regression-tracker-migration
        app.kubernetes.io/name: visual-regression-tracker-migration
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: DATABASE_URL
                  name: visual-regression-tracker-2afdbd
            - name: DEFAULT_USER_EMAIL
              value: admin@vrt.local.walnuts.dev
            - name: DEFAULT_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DEFAULT_USER_PASSWORD
                  name: visual-regression-tracker-2afdbd
            - name: DEFAULT_USER_API_KEY
              valueFrom:
                secretKeyRef:
                  key: DEFAULT_USER_API_KEY
                  name: visual-regression-tracker-2afdbd
          image: docker.io/visualregressiontracker/migration:5.4.0
          imagePullPolicy: IfNotPresent
          name: migration
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - all
            readOnlyRootFilesystem: false
            seccompProfile:
              type: RuntimeDefault
      restartPolicy: Never
