apiVersion: v1
kind: LimitRange
metadata:
  name: coder-workspaces
  namespace: coder-workspaces
spec:
  limits:
    - default:
        cpu: 100m
        memory: 128Mi
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      max:
        cpu: "8"
        memory: 16Gi
      type: Container
    - max:
        storage: 128Gi
      type: PersistentVolumeClaim
