apiVersion: v1
kind: ResourceQuota
metadata:
  name: coder-workspaces
  namespace: coder-workspaces
spec:
  hard:
    count/deployments.apps: "2"
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "2"
    pods: "2"
    requests.cpu: "2"
    requests.memory: 4Gi
    requests.storage: 256Gi
