apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: otel-prometheus-targetallocator-secrets
  namespace: opentelemetry-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: otel-prometheus-targetallocator-secrets
subjects:
  - kind: ServiceAccount
    name: otel-prometheus-targetallocator
    namespace: opentelemetry-collector
