apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: otel-prometheus-targetallocator-secrets
  namespace: opentelemetry-collector
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
