name: Namespace Auto Generation
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: switch to auto-gen-namespace branch
        run: git switch -c auto-gen-namespace

      - name: setup-go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "scripts/infrautil/go.mod"
          cache-dependency-path: "scripts/infrautil/go.sum"

      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
      - name: run namespace
        run: |
          mise run namespace

      - name: check diff
        id: check-diff
        run: |
          echo "diff=$(git diff --name-only | wc -l)" >> $GITHUB_OUTPUT

      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: generate_token
        if: steps.check-diff.outputs.diff > 0
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Set env
        if: steps.check-diff.outputs.diff > 0
        run: |
          echo "GH_TOKEN=${{ steps.generate_token.outputs.token }}" >> $GITHUB_ENV

      - name: push
        if: steps.check-diff.outputs.diff > 0
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "auto-gen-namespace"
          git push origin auto-gen-namespace --force

      - name: create PR
        if: steps.check-diff.outputs.diff > 0
        run: |
          gh pr create --title "auto-gen-namespace" --body "auto-gen-namespace" --base main --head auto-gen-namespace
          gh pr merge --merge --auto
